-- Spell Sprint content pack 2: append-only reference content.
begin;

-- New built-in rules.
insert into public.rules (slug, title, category, rule_type, short_explanation, tts_text, mnemonic, source, visibility, is_active, metadata)
select v.slug, v.title, v.category, v.rule_type, v.short_explanation, v.tts_text, v.mnemonic, 'built-in', 'public', true, v.metadata::jsonb
from (values
  ('advice-vs-advise', 'Advice or advise', 'confusing_words', 'confusing_words', 'Advice is a noun for a suggestion. Advise is a verb meaning to give a suggestion.', 'Listen and choose the correct form.', 'Advice is a thing; advise is an action.', '{"confusable_words": ["advice", "advise"]}'),
  ('accept-vs-except', 'Accept or except', 'confusing_words', 'confusing_words', 'Accept means to agree to take something. Except means not including.', 'Listen and choose the correct form.', 'Accept an offer; except one item.', '{"confusable_words": ["accept", "except"]}'),
  ('then-vs-than', 'Then or than', 'confusing_words', 'confusing_words', 'Then refers to time or the next step. Than is used when comparing things.', 'Listen and choose the correct form.', 'Then is time; than compares.', '{"confusable_words": ["then", "than"]}'),
  ('quiet-vs-quite', 'Quiet or quite', 'confusing_words', 'confusing_words', 'Quiet means making little noise. Quite means fairly or rather.', 'Listen and choose the correct form.', 'Quiet sounds soft; quite means fairly.', '{"confusable_words": ["quiet", "quite"]}'),
  ('weather-vs-whether', 'Weather or whether', 'confusing_words', 'confusing_words', 'Weather is the condition outside. Whether introduces a question or a choice.', 'Listen and choose the correct form.', 'Weather is outside; whether is a choice.', '{"confusable_words": ["weather", "whether"]}'),
  ('principal-vs-principle', 'Principal or principle', 'confusing_words', 'confusing_words', 'Principal means main or a head teacher. Principle is a basic belief or rule.', 'Listen and choose the correct form.', 'Principal is main; principle is a rule.', '{"confusable_words": ["principal", "principle"]}'),
  ('stationary-vs-stationery', 'Stationary or stationery', 'confusing_words', 'confusing_words', 'Stationary means not moving. Stationery means paper and writing supplies.', 'Listen and choose the correct form.', 'Stationery has e for envelopes.', '{"confusable_words": ["stationary", "stationery"]}'),
  ('to-too-two', 'To, too or two', 'confusing_words', 'confusing_words', 'To shows direction or comes before a verb. Too means also or excessively; two means the number 2.', 'Listen and choose the correct form.', 'Two is a number; too is extra.', '{"confusable_words": ["to", "too", "two"]}'),
  ('were-where-wear', 'Were, where or wear', 'confusing_words', 'confusing_words', 'Were is a past form of be. Where asks about a place; wear means to have clothes on.', 'Listen and choose the correct form.', 'Where is a place; wear is clothes.', '{"confusable_words": ["were", "where", "wear"]}'),
  ('practice-vs-practise', 'Practice or practise', 'confusing_words', 'confusing_words', 'In British English, practice is a noun. Practise is a verb.', 'Listen and choose the correct form.', 'Practise with s is something you do.', '{"confusable_words": ["practice", "practise"]}'),
  ('plural-es', 'Plural nouns with -es', 'plural_forms', 'language_rule', 'Add -es to most nouns ending in s, x, z, ch or sh. Box becomes boxes.', 'Listen and choose the correct form.', 'A hissing ending needs an extra e.', '{}'),
  ('plural-f-to-ves', 'Plural nouns with -ves', 'plural_forms', 'language_rule', 'Some nouns ending in f or fe change that ending to -ves in the plural. Knife becomes knives.', 'Listen and choose the correct form.', 'A knife loses fe and gains ves.', '{}'),
  ('irregular-plurals', 'Common irregular plurals', 'irregular_forms_and_exceptions', 'exception', 'Some plural nouns do not use -s or -es. Child becomes children, mouse becomes mice and person becomes people.', 'Listen and choose the correct form.', 'Child becomes children; mouse becomes mice.', '{}'),
  ('irregular-past-common', 'Common irregular past verbs', 'irregular_forms_and_exceptions', 'exception', 'Many common verbs change spelling in the past. Buy becomes bought, teach becomes taught, and think becomes thought.', 'Listen and choose the correct form.', 'Bought, brought and thought share ought.', '{}'),
  ('comparatives-er-est', 'Comparatives with -er and -est', 'english_spelling', 'language_rule', 'Short adjectives often add -er or -est. Double a final consonant after a short vowel, change final y to i, or drop a final e.', 'Listen and choose the correct form.', 'Big doubles; happy changes y; nice drops e.', '{}'),
  ('tion-vs-sion', 'Nouns ending in -tion or -sion', 'prefixes_and_suffixes', 'language_rule', 'Some nouns end in -tion, like information. Others end in -sion, like decision and discussion. Learn the ending with each word.', 'Listen and choose the correct form.', 'Information takes tion; decision takes sion.', '{}'),
  ('ance-vs-ence', 'Nouns ending in -ance or -ence', 'prefixes_and_suffixes', 'language_rule', 'Some nouns end in -ance, like appearance. Others end in -ence, like difference and independence.', 'Listen and choose the correct form.', 'Appearance takes ance; difference takes ence.', '{}'),
  ('soft-c-and-g', 'Keep e after soft c and g', 'vowels_and_letter_patterns', 'language_rule', 'Keep e after soft c or g before a suffix beginning with a or o. Notice becomes noticeable, and courage becomes courageous.', 'Listen and choose the correct form.', 'Keep e so c and g stay soft.', '{}')
) as v(slug, title, category, rule_type, short_explanation, tts_text, mnemonic, metadata)

where not exists (select 1 from public.rules r where r.slug = v.slug);

-- Examples for new and existing rules.
insert into public.rule_examples (rule_id, example_type, text, correction, note)
select r.id, v.example_type, v.text, v.correction, v.note
from (values
  ('advice-vs-advise', 'incorrect', 'I need your advise.', 'I need your advice.', 'The meaning selects this word'),
  ('advice-vs-advise', 'incorrect', 'Please advice me.', 'Please advise me.', 'The meaning selects this word'),
  ('advice-vs-advise', 'correct', 'Her advice helped me choose a course.', null, 'Correct word in context'),
  ('advice-vs-advise', 'correct', 'I advise you to check the details.', null, 'Correct word in context'),
  ('accept-vs-except', 'incorrect', 'I will except the offer.', 'I will accept the offer.', 'The meaning selects this word'),
  ('accept-vs-except', 'incorrect', 'Everyone came accept me.', 'Everyone came except me.', 'The meaning selects this word'),
  ('accept-vs-except', 'correct', 'She decided to accept the invitation.', null, 'Correct word in context'),
  ('accept-vs-except', 'correct', 'All the shops were open except one.', null, 'Correct word in context'),
  ('then-vs-than', 'incorrect', 'She is taller then me.', 'She is taller than me.', 'The meaning selects this word'),
  ('then-vs-than', 'incorrect', 'We ate and than left.', 'We ate and then left.', 'The meaning selects this word'),
  ('then-vs-than', 'correct', 'We finished dinner, then went home.', null, 'Correct word in context'),
  ('then-vs-than', 'correct', 'This coat is warmer than mine.', null, 'Correct word in context'),
  ('quiet-vs-quite', 'incorrect', 'The room was quite after lunch.', 'The room was quiet after lunch.', 'The meaning selects this word'),
  ('quiet-vs-quite', 'incorrect', 'The film was quiet interesting.', 'The film was quite interesting.', 'The meaning selects this word'),
  ('quiet-vs-quite', 'correct', 'The library is quiet in the morning.', null, 'Correct word in context'),
  ('quiet-vs-quite', 'correct', 'The book was quite interesting.', null, 'Correct word in context'),
  ('weather-vs-whether', 'incorrect', 'I wonder weather she is home.', 'I wonder whether she is home.', 'The meaning selects this word'),
  ('weather-vs-whether', 'incorrect', 'The whether is cold today.', 'The weather is cold today.', 'The meaning selects this word'),
  ('weather-vs-whether', 'correct', 'The weather improved before our walk.', null, 'Correct word in context'),
  ('weather-vs-whether', 'correct', 'I asked whether the shop was open.', null, 'Correct word in context'),
  ('principal-vs-principle', 'incorrect', 'Honesty is an important principal.', 'Honesty is an important principle.', 'The meaning selects this word'),
  ('principal-vs-principle', 'incorrect', 'The principle reason was cost.', 'The principal reason was cost.', 'The meaning selects this word'),
  ('principal-vs-principle', 'correct', 'The principal reason was the price.', null, 'Correct word in context'),
  ('principal-vs-principle', 'correct', 'Fairness is an important principle.', null, 'Correct word in context'),
  ('stationary-vs-stationery', 'incorrect', 'The car stayed stationery.', 'The car stayed stationary.', 'The meaning selects this word'),
  ('stationary-vs-stationery', 'incorrect', 'We need more stationary for the office.', 'We need more stationery for the office.', 'The meaning selects this word'),
  ('stationary-vs-stationery', 'correct', 'The train remained stationary at the platform.', null, 'Correct word in context'),
  ('stationary-vs-stationery', 'correct', 'I bought stationery for my class.', null, 'Correct word in context'),
  ('to-too-two', 'incorrect', 'I have to sisters.', 'I have two sisters.', 'The meaning selects this word'),
  ('to-too-two', 'incorrect', 'This bag is two heavy.', 'This bag is too heavy.', 'The meaning selects this word'),
  ('to-too-two', 'correct', 'We walked to the park after lunch.', null, 'Correct word in context'),
  ('to-too-two', 'correct', 'The two boys wanted to come too.', null, 'Correct word in context'),
  ('were-where-wear', 'incorrect', 'Where you at home yesterday?', 'Were you at home yesterday?', 'The meaning selects this word'),
  ('were-where-wear', 'incorrect', 'I will where a coat.', 'I will wear a coat.', 'The meaning selects this word'),
  ('were-where-wear', 'correct', 'We were tired after the walk.', null, 'Correct word in context'),
  ('were-where-wear', 'correct', 'Where do you wear that jacket?', null, 'Correct word in context'),
  ('practice-vs-practise', 'incorrect', 'Daily practise is useful.', 'Daily practice is useful.', 'The meaning selects this word'),
  ('practice-vs-practise', 'incorrect', 'I want to practice speaking.', 'I want to practise speaking.', 'The meaning selects this word'),
  ('practice-vs-practise', 'correct', 'Regular practice improves spelling.', null, 'Correct word in context'),
  ('practice-vs-practise', 'correct', 'I practise speaking English each morning.', null, 'Correct word in context'),
  ('plural-es', 'incorrect', 'boxs', 'boxes', 'Correct the spelling of this form'),
  ('plural-es', 'incorrect', 'watchs', 'watches', 'Correct the spelling of this form'),
  ('plural-es', 'correct', 'We packed the boxes before lunch.', null, 'Correct spelling in context'),
  ('plural-es', 'correct', 'She wears two watches on special occasions.', null, 'Correct spelling in context'),
  ('plural-es', 'exception', 'stomach → stomachs', null, 'Hard ch sound takes only s'),
  ('plural-f-to-ves', 'incorrect', 'knifes', 'knives', 'Correct the spelling of this form'),
  ('plural-f-to-ves', 'incorrect', 'wifes', 'wives', 'Correct the spelling of this form'),
  ('plural-f-to-ves', 'correct', 'The knives are in the kitchen drawer.', null, 'Correct spelling in context'),
  ('plural-f-to-ves', 'correct', 'Several leaves fell from the tree.', null, 'Correct spelling in context'),
  ('plural-f-to-ves', 'exception', 'roof → roofs; chef → chefs', null, 'These nouns keep f and add s'),
  ('irregular-plurals', 'incorrect', 'childs', 'children', 'Correct the spelling of this form'),
  ('irregular-plurals', 'incorrect', 'mouses', 'mice', 'Correct the spelling of this form'),
  ('irregular-plurals', 'correct', 'The children played outside all afternoon.', null, 'Correct spelling in context'),
  ('irregular-plurals', 'correct', 'Two mice ran across the floor.', null, 'Correct spelling in context'),
  ('irregular-past-common', 'incorrect', 'buyed', 'bought', 'Correct the spelling of this form'),
  ('irregular-past-common', 'incorrect', 'teached', 'taught', 'Correct the spelling of this form'),
  ('irregular-past-common', 'correct', 'She bought some bread yesterday.', null, 'Correct spelling in context'),
  ('irregular-past-common', 'correct', 'The teacher taught us a new song.', null, 'Correct spelling in context'),
  ('comparatives-er-est', 'incorrect', 'biger', 'bigger', 'Correct the spelling of this form'),
  ('comparatives-er-est', 'incorrect', 'happyer', 'happier', 'Correct the spelling of this form'),
  ('comparatives-er-est', 'correct', 'This room is bigger than ours.', null, 'Correct spelling in context'),
  ('comparatives-er-est', 'correct', 'She chose the nicest cake.', null, 'Correct spelling in context'),
  ('comparatives-er-est', 'exception', 'good → better → best', null, 'Good uses irregular comparison forms'),
  ('tion-vs-sion', 'incorrect', 'informasion', 'information', 'Correct the spelling of this form'),
  ('tion-vs-sion', 'incorrect', 'decition', 'decision', 'Correct the spelling of this form'),
  ('tion-vs-sion', 'correct', 'The information was easy to find.', null, 'Correct spelling in context'),
  ('tion-vs-sion', 'correct', 'We had a discussion after the film.', null, 'Correct spelling in context'),
  ('ance-vs-ence', 'incorrect', 'appearence', 'appearance', 'Correct the spelling of this form'),
  ('ance-vs-ence', 'incorrect', 'independance', 'independence', 'Correct the spelling of this form'),
  ('ance-vs-ence', 'correct', 'Her appearance changed over the years.', null, 'Correct spelling in context'),
  ('ance-vs-ence', 'correct', 'Their independence matters to them.', null, 'Correct spelling in context'),
  ('soft-c-and-g', 'incorrect', 'noticable', 'noticeable', 'Correct the spelling of this form'),
  ('soft-c-and-g', 'incorrect', 'couragous', 'courageous', 'Correct the spelling of this form'),
  ('soft-c-and-g', 'correct', 'The change was noticeable after a week.', null, 'Correct spelling in context'),
  ('soft-c-and-g', 'correct', 'It was courageous of her to speak up.', null, 'Correct spelling in context'),
  ('double-consonants', 'incorrect', 'adress', 'address', 'Correct the relevant rule here'),
  ('double-consonants', 'incorrect', 'succes', 'success', 'Correct the relevant rule here'),
  ('double-consonants', 'correct', 'Write your address clearly on the form.', null, 'Correct use in context'),
  ('vowel-order-ei-ie', 'incorrect', 'recieve', 'receive', 'Correct the relevant rule here'),
  ('vowel-order-ei-ie', 'incorrect', 'freind', 'friend', 'Correct the relevant rule here'),
  ('vowel-order-ei-ie', 'correct', 'My friend waited near the entrance.', null, 'Correct use in context'),
  ('lose-vs-loose', 'incorrect', 'Do not loose the ticket.', 'Do not lose the ticket.', 'Correct the relevant rule here'),
  ('lose-vs-loose', 'incorrect', 'The rope is lose.', 'The rope is loose.', 'Correct the relevant rule here'),
  ('lose-vs-loose', 'correct', 'The lid was loose, so I nearly lost it.', null, 'Correct use in context'),
  ('plural-y-to-ies', 'incorrect', 'cherrys', 'cherries', 'Correct the relevant rule here'),
  ('plural-y-to-ies', 'incorrect', 'dairys', 'dairies', 'Correct the relevant rule here'),
  ('plural-y-to-ies', 'correct', 'The berries were fresh and sweet.', null, 'Correct use in context'),
  ('irregular-past-go', 'incorrect', 'She goed home.', 'She went home.', 'Correct the relevant rule here'),
  ('irregular-past-go', 'incorrect', 'He has went home.', 'He has gone home.', 'Correct the relevant rule here'),
  ('irregular-past-go', 'correct', 'After lunch, they went to the park.', null, 'Correct use in context'),
  ('there-vs-their', 'incorrect', 'The coats are over their.', 'The coats are over there.', 'Correct the relevant rule here'),
  ('there-vs-their', 'incorrect', 'There house is small.', 'Their house is small.', 'Correct the relevant rule here'),
  ('there-vs-their', 'correct', 'They left their coats there by the door.', null, 'Correct use in context'),
  ('its-vs-its-contraction', 'incorrect', 'Its a sunny day.', 'It''s a sunny day.', 'Correct the relevant rule here'),
  ('its-vs-its-contraction', 'incorrect', 'The dog ate it''s food.', 'The dog ate its food.', 'Correct the relevant rule here'),
  ('its-vs-its-contraction', 'correct', 'The bird opened its wings because it''s ready to fly.', null, 'Correct use in context'),
  ('your-vs-youre', 'incorrect', 'Your very kind.', 'You''re very kind.', 'Correct the relevant rule here'),
  ('your-vs-youre', 'incorrect', 'You''re bag is heavy.', 'Your bag is heavy.', 'Correct the relevant rule here'),
  ('your-vs-youre', 'correct', 'Your brother said you''re coming soon.', null, 'Correct use in context'),
  ('affect-vs-effect', 'incorrect', 'Noise can effect sleep.', 'Noise can affect sleep.', 'Correct the relevant rule here'),
  ('affect-vs-effect', 'incorrect', 'The new rule had an affect.', 'The new rule had an effect.', 'Correct the relevant rule here'),
  ('affect-vs-effect', 'correct', 'The cold may affect how quickly the medicine takes effect.', null, 'Correct use in context'),
  ('silent-letters', 'incorrect', 'nife', 'knife', 'Correct the relevant rule here'),
  ('silent-letters', 'incorrect', 'lam', 'lamb', 'Keep the silent final b'),
  ('silent-letters', 'correct', 'The lamb slept beside the old fence.', null, 'Correct use in context'),
  ('drop-silent-e', 'incorrect', 'moveing', 'moving', 'Correct the relevant rule here'),
  ('drop-silent-e', 'incorrect', 'hopeing', 'hoping', 'Correct the relevant rule here'),
  ('drop-silent-e', 'correct', 'She smiled while moving the chairs.', null, 'Correct use in context'),
  ('double-before-ing-ed', 'incorrect', 'runing', 'running', 'Correct the relevant rule here'),
  ('double-before-ing-ed', 'incorrect', 'sliped', 'slipped', 'Correct the relevant rule here'),
  ('double-before-ing-ed', 'correct', 'They were running through the park together.', null, 'Correct use in context'),
  ('suffix-ful', 'incorrect', 'hopefull', 'hopeful', 'Correct the relevant rule here'),
  ('suffix-ful', 'incorrect', 'cheerfull', 'cheerful', 'Correct the relevant rule here'),
  ('suffix-ful', 'correct', 'Her cheerful voice made everyone smile.', null, 'Correct use in context'),
  ('adverbs-ly', 'incorrect', 'quickley', 'quickly', 'Correct the relevant rule here'),
  ('adverbs-ly', 'incorrect', 'slowley', 'slowly', 'Correct the relevant rule here'),
  ('adverbs-ly', 'correct', 'She answered the question quickly and clearly.', null, 'Correct use in context'),
  ('able-vs-ible', 'incorrect', 'accessable', 'accessible', 'Correct the relevant rule here'),
  ('able-vs-ible', 'incorrect', 'readible', 'readable', 'Correct the relevant rule here'),
  ('able-vs-ible', 'correct', 'The menu was readable even in poor light.', null, 'Correct use in context')
) as v(slug, example_type, text, correction, note)
join public.rules r on r.slug = v.slug
where not exists (select 1 from public.rule_examples e where e.rule_id = r.id and e.example_type = v.example_type and e.text = v.text);

-- Challenge exercises.
insert into public.rule_exercises (rule_id, exercise_type, prompt, answer, choices, metadata)
select r.id, v.exercise_type, v.prompt, v.answer, v.choices::jsonb, v.metadata::jsonb
from (values
  ('advice-vs-advise', 'fill_gap', 'I need some ___ before deciding.', 'advice', null, '{"set": "challenge-v1", "word": "advice", "pack": "content-2"}'),
  ('advice-vs-advise', 'fill_gap', 'Can you ___ me about the course?', 'advise', null, '{"set": "challenge-v1", "word": "advise", "pack": "content-2"}'),
  ('advice-vs-advise', 'fill_gap', 'His ___ was very helpful.', 'advice', null, '{"set": "challenge-v1", "word": "advice", "pack": "content-2"}'),
  ('advice-vs-advise', 'fill_gap', 'Doctors often ___ patients to rest.', 'advise', null, '{"set": "challenge-v1", "word": "advise", "pack": "content-2"}'),
  ('advice-vs-advise', 'fill_gap', 'That was good ___.', 'advice', null, '{"set": "challenge-v1", "word": "advice", "pack": "content-2"}'),
  ('advice-vs-advise', 'multiple_choice', 'Choose the word: I asked for your ___.', 'advice', '["advice", "advise"]', '{"set": "challenge-v1", "word": "advice", "pack": "content-2"}'),
  ('advice-vs-advise', 'multiple_choice', 'Choose the word: They ___ us to wait.', 'advise', '["advice", "advise"]', '{"set": "challenge-v1", "word": "advise", "pack": "content-2"}'),
  ('advice-vs-advise', 'multiple_choice', 'Choose the word: Could you offer some ___?', 'advice', '["advice", "advise"]', '{"set": "challenge-v1", "word": "advice", "pack": "content-2"}'),
  ('accept-vs-except', 'fill_gap', 'Please ___ this gift.', 'accept', null, '{"set": "challenge-v1", "word": "accept", "pack": "content-2"}'),
  ('accept-vs-except', 'fill_gap', 'Everyone ___ me was ready.', 'except', null, '{"set": "challenge-v1", "word": "except", "pack": "content-2"}'),
  ('accept-vs-except', 'fill_gap', 'Will you ___ the invitation?', 'accept', null, '{"set": "challenge-v1", "word": "accept", "pack": "content-2"}'),
  ('accept-vs-except', 'fill_gap', 'The shop opens daily ___ Sunday.', 'except', null, '{"set": "challenge-v1", "word": "except", "pack": "content-2"}'),
  ('accept-vs-except', 'fill_gap', 'I cannot ___ that price.', 'accept', null, '{"set": "challenge-v1", "word": "accept", "pack": "content-2"}'),
  ('accept-vs-except', 'multiple_choice', 'Choose the word: I eat everything ___ fish.', 'except', '["accept", "except"]', '{"set": "challenge-v1", "word": "except", "pack": "content-2"}'),
  ('accept-vs-except', 'multiple_choice', 'Choose the word: Did they ___ your offer?', 'accept', '["accept", "except"]', '{"set": "challenge-v1", "word": "accept", "pack": "content-2"}'),
  ('accept-vs-except', 'multiple_choice', 'Choose the word: All seats ___ one were taken.', 'except', '["accept", "except"]', '{"set": "challenge-v1", "word": "except", "pack": "content-2"}'),
  ('then-vs-than', 'fill_gap', 'We ate and ___ left.', 'then', null, '{"set": "challenge-v1", "word": "then", "pack": "content-2"}'),
  ('then-vs-than', 'fill_gap', 'This costs more ___ that.', 'than', null, '{"set": "challenge-v1", "word": "than", "pack": "content-2"}'),
  ('then-vs-than', 'fill_gap', 'Wash your hands, ___ eat.', 'then', null, '{"set": "challenge-v1", "word": "then", "pack": "content-2"}'),
  ('then-vs-than', 'fill_gap', 'He is younger ___ his sister.', 'than', null, '{"set": "challenge-v1", "word": "than", "pack": "content-2"}'),
  ('then-vs-than', 'fill_gap', 'The lights went out; ___ it rained.', 'then', null, '{"set": "challenge-v1", "word": "then", "pack": "content-2"}'),
  ('then-vs-than', 'multiple_choice', 'Choose the word: I would rather walk ___ drive.', 'than', '["then", "than"]', '{"set": "challenge-v1", "word": "than", "pack": "content-2"}'),
  ('then-vs-than', 'multiple_choice', 'Choose the word: We can talk about it ___.', 'then', '["then", "than"]', '{"set": "challenge-v1", "word": "then", "pack": "content-2"}'),
  ('then-vs-than', 'multiple_choice', 'Choose the word: It was harder ___ expected.', 'than', '["then", "than"]', '{"set": "challenge-v1", "word": "than", "pack": "content-2"}'),
  ('quiet-vs-quite', 'fill_gap', 'Please stay ___ during the film.', 'quiet', null, '{"set": "challenge-v1", "word": "quiet", "pack": "content-2"}'),
  ('quiet-vs-quite', 'fill_gap', 'It is ___ warm today.', 'quite', null, '{"set": "challenge-v1", "word": "quite", "pack": "content-2"}'),
  ('quiet-vs-quite', 'fill_gap', 'The street is usually ___.', 'quiet', null, '{"set": "challenge-v1", "word": "quiet", "pack": "content-2"}'),
  ('quiet-vs-quite', 'fill_gap', 'She was ___ pleased.', 'quite', null, '{"set": "challenge-v1", "word": "quite", "pack": "content-2"}'),
  ('quiet-vs-quite', 'fill_gap', 'The room became ___ after six.', 'quiet', null, '{"set": "challenge-v1", "word": "quiet", "pack": "content-2"}'),
  ('quiet-vs-quite', 'multiple_choice', 'Choose the word: This tea is ___ hot.', 'quite', '["quiet", "quite"]', '{"set": "challenge-v1", "word": "quite", "pack": "content-2"}'),
  ('quiet-vs-quite', 'multiple_choice', 'Choose the word: Please be ___ during the test.', 'quiet', '["quiet", "quite"]', '{"set": "challenge-v1", "word": "quiet", "pack": "content-2"}'),
  ('quiet-vs-quite', 'multiple_choice', 'Choose the word: The task is ___ simple.', 'quite', '["quiet", "quite"]', '{"set": "challenge-v1", "word": "quite", "pack": "content-2"}'),
  ('weather-vs-whether', 'fill_gap', 'The ___ may change soon.', 'weather', null, '{"set": "challenge-v1", "word": "weather", "pack": "content-2"}'),
  ('weather-vs-whether', 'fill_gap', 'I cannot decide ___ to go.', 'whether', null, '{"set": "challenge-v1", "word": "whether", "pack": "content-2"}'),
  ('weather-vs-whether', 'fill_gap', 'We checked the ___ before leaving.', 'weather', null, '{"set": "challenge-v1", "word": "weather", "pack": "content-2"}'),
  ('weather-vs-whether', 'fill_gap', 'She asked ___ I needed help.', 'whether', null, '{"set": "challenge-v1", "word": "whether", "pack": "content-2"}'),
  ('weather-vs-whether', 'fill_gap', 'Bad ___ kept us inside.', 'weather', null, '{"set": "challenge-v1", "word": "weather", "pack": "content-2"}'),
  ('weather-vs-whether', 'multiple_choice', 'Choose the word: Tell me ___ you agree.', 'whether', '["weather", "whether"]', '{"set": "challenge-v1", "word": "whether", "pack": "content-2"}'),
  ('weather-vs-whether', 'multiple_choice', 'Choose the word: The ___ was lovely yesterday.', 'weather', '["weather", "whether"]', '{"set": "challenge-v1", "word": "weather", "pack": "content-2"}'),
  ('weather-vs-whether', 'multiple_choice', 'Choose the word: I do not know ___ he called.', 'whether', '["weather", "whether"]', '{"set": "challenge-v1", "word": "whether", "pack": "content-2"}'),
  ('principal-vs-principle', 'fill_gap', 'The school ___ welcomed us.', 'principal', null, '{"set": "challenge-v1", "word": "principal", "pack": "content-2"}'),
  ('principal-vs-principle', 'fill_gap', 'Fairness is a useful ___.', 'principle', null, '{"set": "challenge-v1", "word": "principle", "pack": "content-2"}'),
  ('principal-vs-principle', 'fill_gap', 'The ___ problem is the cost.', 'principal', null, '{"set": "challenge-v1", "word": "principal", "pack": "content-2"}'),
  ('principal-vs-principle', 'fill_gap', 'He refused to lie on ___.', 'principle', null, '{"set": "challenge-v1", "word": "principle", "pack": "content-2"}'),
  ('principal-vs-principle', 'fill_gap', 'The ___ spoke at the meeting.', 'principal', null, '{"set": "challenge-v1", "word": "principal", "pack": "content-2"}'),
  ('principal-vs-principle', 'multiple_choice', 'Choose the word: Our ___ reason is time.', 'principal', '["principal", "principle"]', '{"set": "challenge-v1", "word": "principal", "pack": "content-2"}'),
  ('principal-vs-principle', 'multiple_choice', 'Choose the word: It is a matter of ___.', 'principle', '["principal", "principle"]', '{"set": "challenge-v1", "word": "principle", "pack": "content-2"}'),
  ('principal-vs-principle', 'multiple_choice', 'Choose the word: The school ___ called home.', 'principal', '["principal", "principle"]', '{"set": "challenge-v1", "word": "principal", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'fill_gap', 'The bicycle was ___.', 'stationary', null, '{"set": "challenge-v1", "word": "stationary", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'fill_gap', 'She bought ___ for school.', 'stationery', null, '{"set": "challenge-v1", "word": "stationery", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'fill_gap', 'The bus remained ___.', 'stationary', null, '{"set": "challenge-v1", "word": "stationary", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'fill_gap', 'We keep ___ in the cupboard.', 'stationery', null, '{"set": "challenge-v1", "word": "stationery", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'fill_gap', 'The camera must stay ___.', 'stationary', null, '{"set": "challenge-v1", "word": "stationary", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'multiple_choice', 'Choose the word: We need new ___ for the office.', 'stationery', '["stationary", "stationery"]', '{"set": "challenge-v1", "word": "stationery", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'multiple_choice', 'Choose the word: The vehicle stayed ___.', 'stationary', '["stationary", "stationery"]', '{"set": "challenge-v1", "word": "stationary", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'multiple_choice', 'Choose the word: Pens are a type of ___.', 'stationery', '["stationary", "stationery"]', '{"set": "challenge-v1", "word": "stationery", "pack": "content-2"}'),
  ('to-too-two', 'fill_gap', 'I need ___ buy milk.', 'to', null, '{"set": "challenge-v1", "word": "to", "pack": "content-2"}'),
  ('to-too-two', 'fill_gap', 'There are ___ chairs here.', 'two', null, '{"set": "challenge-v1", "word": "two", "pack": "content-2"}'),
  ('to-too-two', 'fill_gap', 'This soup is ___ hot.', 'too', null, '{"set": "challenge-v1", "word": "too", "pack": "content-2"}'),
  ('to-too-two', 'fill_gap', 'She went ___ the library.', 'to', null, '{"set": "challenge-v1", "word": "to", "pack": "content-2"}'),
  ('to-too-two', 'fill_gap', 'Can I come ___?', 'too', null, '{"set": "challenge-v1", "word": "too", "pack": "content-2"}'),
  ('to-too-two', 'multiple_choice', 'Choose the word: I have ___ tickets.', 'two', '["to", "too", "two"]', '{"set": "challenge-v1", "word": "two", "pack": "content-2"}'),
  ('to-too-two', 'multiple_choice', 'Choose the word: The box is ___ heavy.', 'too', '["to", "too", "two"]', '{"set": "challenge-v1", "word": "too", "pack": "content-2"}'),
  ('to-too-two', 'multiple_choice', 'Choose the word: We plan ___ leave.', 'to', '["to", "too", "two"]', '{"set": "challenge-v1", "word": "to", "pack": "content-2"}'),
  ('were-where-wear', 'fill_gap', 'We ___ late yesterday.', 'were', null, '{"set": "challenge-v1", "word": "were", "pack": "content-2"}'),
  ('were-where-wear', 'fill_gap', '___ is the nearest stop?', 'where', null, '{"set": "challenge-v1", "word": "where", "pack": "content-2"}'),
  ('were-where-wear', 'fill_gap', 'You should ___ a coat.', 'wear', null, '{"set": "challenge-v1", "word": "wear", "pack": "content-2"}'),
  ('were-where-wear', 'fill_gap', 'The children ___ excited.', 'were', null, '{"set": "challenge-v1", "word": "were", "pack": "content-2"}'),
  ('were-where-wear', 'fill_gap', 'Do you know ___ she lives?', 'where', null, '{"set": "challenge-v1", "word": "where", "pack": "content-2"}'),
  ('were-where-wear', 'multiple_choice', 'Choose the word: I always ___ comfortable shoes.', 'wear', '["were", "where", "wear"]', '{"set": "challenge-v1", "word": "wear", "pack": "content-2"}'),
  ('were-where-wear', 'multiple_choice', 'Choose the word: They ___ at home yesterday.', 'were', '["were", "where", "wear"]', '{"set": "challenge-v1", "word": "were", "pack": "content-2"}'),
  ('were-where-wear', 'multiple_choice', 'Choose the word: Tell me ___ you found it.', 'where', '["were", "where", "wear"]', '{"set": "challenge-v1", "word": "where", "pack": "content-2"}'),
  ('practice-vs-practise', 'fill_gap', 'I need more ___ before the exam.', 'practice', null, '{"set": "challenge-v1", "word": "practice", "pack": "content-2"}'),
  ('practice-vs-practise', 'fill_gap', 'We ___ every Tuesday.', 'practise', null, '{"set": "challenge-v1", "word": "practise", "pack": "content-2"}'),
  ('practice-vs-practise', 'fill_gap', 'Her piano ___ lasts an hour.', 'practice', null, '{"set": "challenge-v1", "word": "practice", "pack": "content-2"}'),
  ('practice-vs-practise', 'fill_gap', 'Try to ___ these words.', 'practise', null, '{"set": "challenge-v1", "word": "practise", "pack": "content-2"}'),
  ('practice-vs-practise', 'fill_gap', 'The team had extra ___ today.', 'practice', null, '{"set": "challenge-v1", "word": "practice", "pack": "content-2"}'),
  ('practice-vs-practise', 'multiple_choice', 'Choose the word: I ___ for an hour daily.', 'practise', '["practice", "practise"]', '{"set": "challenge-v1", "word": "practise", "pack": "content-2"}'),
  ('practice-vs-practise', 'multiple_choice', 'Choose the word: Regular ___ is useful.', 'practice', '["practice", "practise"]', '{"set": "challenge-v1", "word": "practice", "pack": "content-2"}'),
  ('practice-vs-practise', 'multiple_choice', 'Choose the word: You should ___ your pronunciation.', 'practise', '["practice", "practise"]', '{"set": "challenge-v1", "word": "practise", "pack": "content-2"}'),
  ('plural-es', 'correct_word', 'brushs', 'brushes', null, '{"set": "challenge-v1", "word": "brushes", "pack": "content-2"}'),
  ('plural-es', 'correct_word', 'kisss', 'kisses', null, '{"set": "challenge-v1", "word": "kisses", "pack": "content-2"}'),
  ('plural-es', 'correct_word', 'buss', 'buses', null, '{"set": "challenge-v1", "word": "buses", "pack": "content-2"}'),
  ('plural-es', 'spell', 'Spell the word: more than one fox.', 'foxes', null, '{"set": "challenge-v1", "word": "foxes", "pack": "content-2"}'),
  ('plural-es', 'spell', 'Spell the word: more than one glass.', 'glasses', null, '{"set": "challenge-v1", "word": "glasses", "pack": "content-2"}'),
  ('plural-es', 'fill_gap', 'The two ___ helped the team. (тренеры)', 'coaches', null, '{"set": "challenge-v1", "word": "coaches", "pack": "content-2"}'),
  ('plural-es', 'fill_gap', 'The new ___ looked smart. (платья)', 'dresses', null, '{"set": "challenge-v1", "word": "dresses", "pack": "content-2"}'),
  ('plural-es', 'multiple_choice', 'Choose the correct plural of quiz.', 'quizzes', '["quizzes", "quizs", "quizes"]', '{"set": "challenge-v1", "word": "quizzes", "pack": "content-2"}'),
  ('plural-f-to-ves', 'correct_word', 'shelfs', 'shelves', null, '{"set": "challenge-v1", "word": "shelves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'correct_word', 'lifes', 'lives', null, '{"set": "challenge-v1", "word": "lives", "pack": "content-2"}'),
  ('plural-f-to-ves', 'correct_word', 'wolfs', 'wolves', null, '{"set": "challenge-v1", "word": "wolves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'spell', 'Spell the word: more than one thief.', 'thieves', null, '{"set": "challenge-v1", "word": "thieves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'spell', 'Spell the word: more than one loaf.', 'loaves', null, '{"set": "challenge-v1", "word": "loaves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'fill_gap', 'The ___ turned yellow in autumn. (листья)', 'leaves', null, '{"set": "challenge-v1", "word": "leaves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'fill_gap', 'The ___ stood near their mothers. (телята)', 'calves', null, '{"set": "challenge-v1", "word": "calves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'multiple_choice', 'Choose the correct plural of half.', 'halves', '["halves", "halfs", "halfes"]', '{"set": "challenge-v1", "word": "halves", "pack": "content-2"}'),
  ('irregular-plurals', 'correct_word', 'mans', 'men', null, '{"set": "challenge-v1", "word": "men", "pack": "content-2"}'),
  ('irregular-plurals', 'correct_word', 'womans', 'women', null, '{"set": "challenge-v1", "word": "women", "pack": "content-2"}'),
  ('irregular-plurals', 'correct_word', 'tooths', 'teeth', null, '{"set": "challenge-v1", "word": "teeth", "pack": "content-2"}'),
  ('irregular-plurals', 'spell', 'Spell the word: more than one foot.', 'feet', null, '{"set": "challenge-v1", "word": "feet", "pack": "content-2"}'),
  ('irregular-plurals', 'spell', 'Spell the word: more than one goose.', 'geese', null, '{"set": "challenge-v1", "word": "geese", "pack": "content-2"}'),
  ('irregular-plurals', 'fill_gap', 'Three ___ waited outside. (человека)', 'people', null, '{"set": "challenge-v1", "word": "people", "pack": "content-2"}'),
  ('irregular-plurals', 'fill_gap', 'The ___ played quietly. (дети)', 'children', null, '{"set": "challenge-v1", "word": "children", "pack": "content-2"}'),
  ('irregular-plurals', 'multiple_choice', 'Choose the correct plural of mouse.', 'mice', '["mice", "mouses", "mices"]', '{"set": "challenge-v1", "word": "mice", "pack": "content-2"}'),
  ('irregular-past-common', 'correct_word', 'thinked', 'thought', null, '{"set": "challenge-v1", "word": "thought", "pack": "content-2"}'),
  ('irregular-past-common', 'correct_word', 'bringed', 'brought', null, '{"set": "challenge-v1", "word": "brought", "pack": "content-2"}'),
  ('irregular-past-common', 'correct_word', 'catched', 'caught', null, '{"set": "challenge-v1", "word": "caught", "pack": "content-2"}'),
  ('irregular-past-common', 'spell', 'Spell the word: the past form of buy.', 'bought', null, '{"set": "challenge-v1", "word": "bought", "pack": "content-2"}'),
  ('irregular-past-common', 'spell', 'Spell the word: the past form of teach.', 'taught', null, '{"set": "challenge-v1", "word": "taught", "pack": "content-2"}'),
  ('irregular-past-common', 'fill_gap', 'She ___ her old bicycle last week. (продала)', 'sold', null, '{"set": "challenge-v1", "word": "sold", "pack": "content-2"}'),
  ('irregular-past-common', 'fill_gap', 'He ___ a letter yesterday. (написал)', 'wrote', null, '{"set": "challenge-v1", "word": "wrote", "pack": "content-2"}'),
  ('irregular-past-common', 'multiple_choice', 'Choose the correct past form of feel.', 'felt', '["felt", "feeled", "felled"]', '{"set": "challenge-v1", "word": "felt", "pack": "content-2"}'),
  ('comparatives-er-est', 'correct_word', 'hoter', 'hotter', null, '{"set": "challenge-v1", "word": "hotter", "pack": "content-2"}'),
  ('comparatives-er-est', 'correct_word', 'easyer', 'easier', null, '{"set": "challenge-v1", "word": "easier", "pack": "content-2"}'),
  ('comparatives-er-est', 'correct_word', 'niceer', 'nicer', null, '{"set": "challenge-v1", "word": "nicer", "pack": "content-2"}'),
  ('comparatives-er-est', 'spell', 'Spell the word: the comparative form of sad.', 'sadder', null, '{"set": "challenge-v1", "word": "sadder", "pack": "content-2"}'),
  ('comparatives-er-est', 'spell', 'Spell the word: the superlative form of funny.', 'funniest', null, '{"set": "challenge-v1", "word": "funniest", "pack": "content-2"}'),
  ('comparatives-er-est', 'fill_gap', 'Today is ___ than yesterday. (теплее)', 'warmer', null, '{"set": "challenge-v1", "word": "warmer", "pack": "content-2"}'),
  ('comparatives-er-est', 'fill_gap', 'This is the ___ street nearby. (самая узкая)', 'narrowest', null, '{"set": "challenge-v1", "word": "narrowest", "pack": "content-2"}'),
  ('comparatives-er-est', 'multiple_choice', 'Choose the comparative of heavy.', 'heavier', '["heavier", "heavyer", "heavyr"]', '{"set": "challenge-v1", "word": "heavier", "pack": "content-2"}'),
  ('tion-vs-sion', 'correct_word', 'celebrasion', 'celebration', null, '{"set": "challenge-v1", "word": "celebration", "pack": "content-2"}'),
  ('tion-vs-sion', 'correct_word', 'expantion', 'expansion', null, '{"set": "challenge-v1", "word": "expansion", "pack": "content-2"}'),
  ('tion-vs-sion', 'correct_word', 'confution', 'confusion', null, '{"set": "challenge-v1", "word": "confusion", "pack": "content-2"}'),
  ('tion-vs-sion', 'spell', 'Spell the word: a talk in which people share ideas.', 'discussion', null, '{"set": "challenge-v1", "word": "discussion", "pack": "content-2"}'),
  ('tion-vs-sion', 'spell', 'Spell the word: a choice made after thinking.', 'decision', null, '{"set": "challenge-v1", "word": "decision", "pack": "content-2"}'),
  ('tion-vs-sion', 'fill_gap', 'Her ___ was clear and short. (презентация)', 'presentation', null, '{"set": "challenge-v1", "word": "presentation", "pack": "content-2"}'),
  ('tion-vs-sion', 'fill_gap', 'His ___ surprised the group. (признание)', 'admission', null, '{"set": "challenge-v1", "word": "admission", "pack": "content-2"}'),
  ('tion-vs-sion', 'multiple_choice', 'Choose the correct spelling of a final result.', 'conclusion', '["conclusion", "conclution", "concluson"]', '{"set": "challenge-v1", "word": "conclusion", "pack": "content-2"}'),
  ('ance-vs-ence', 'correct_word', 'preferance', 'preference', null, '{"set": "challenge-v1", "word": "preference", "pack": "content-2"}'),
  ('ance-vs-ence', 'correct_word', 'attendence', 'attendance', null, '{"set": "challenge-v1", "word": "attendance", "pack": "content-2"}'),
  ('ance-vs-ence', 'correct_word', 'importence', 'importance', null, '{"set": "challenge-v1", "word": "importance", "pack": "content-2"}'),
  ('ance-vs-ence', 'spell', 'Spell the word: the ability to wait calmly.', 'patience', null, '{"set": "challenge-v1", "word": "patience", "pack": "content-2"}'),
  ('ance-vs-ence', 'spell', 'Spell the word: help offered to someone.', 'assistance', null, '{"set": "challenge-v1", "word": "assistance", "pack": "content-2"}'),
  ('ance-vs-ence', 'fill_gap', 'Her ___ grew with experience. (уверенность)', 'confidence', null, '{"set": "challenge-v1", "word": "confidence", "pack": "content-2"}'),
  ('ance-vs-ence', 'fill_gap', 'The room fell into ___. (тишину)', 'silence', null, '{"set": "challenge-v1", "word": "silence", "pack": "content-2"}'),
  ('ance-vs-ence', 'multiple_choice', 'Choose the correct spelling of the noun for being absent.', 'absence', '["absence", "absance", "absense"]', '{"set": "challenge-v1", "word": "absence", "pack": "content-2"}'),
  ('soft-c-and-g', 'correct_word', 'servicable', 'serviceable', null, '{"set": "challenge-v1", "word": "serviceable", "pack": "content-2"}'),
  ('soft-c-and-g', 'correct_word', 'knowledgable', 'knowledgeable', null, '{"set": "challenge-v1", "word": "knowledgeable", "pack": "content-2"}'),
  ('soft-c-and-g', 'correct_word', 'tracable', 'traceable', null, '{"set": "challenge-v1", "word": "traceable", "pack": "content-2"}'),
  ('soft-c-and-g', 'spell', 'Spell the word: easy to notice.', 'noticeable', null, '{"set": "challenge-v1", "word": "noticeable", "pack": "content-2"}'),
  ('soft-c-and-g', 'spell', 'Spell the word: brave in a difficult situation.', 'courageous', null, '{"set": "challenge-v1", "word": "courageous", "pack": "content-2"}'),
  ('soft-c-and-g', 'fill_gap', 'The worn part is easily ___. (заменяемая)', 'replaceable', null, '{"set": "challenge-v1", "word": "replaceable", "pack": "content-2"}'),
  ('soft-c-and-g', 'fill_gap', 'The new timetable is busy but ___. (посильный)', 'manageable', null, '{"set": "challenge-v1", "word": "manageable", "pack": "content-2"}'),
  ('soft-c-and-g', 'multiple_choice', 'Choose the spelling for able to change.', 'changeable', '["changeable", "changable", "changeible"]', '{"set": "challenge-v1", "word": "changeable", "pack": "content-2"}'),
  ('double-consonants', 'correct_word', 'adres', 'address', null, '{"set": "challenge-v1", "word": "address", "pack": "content-2"}'),
  ('double-consonants', 'spell', 'Spell the word: a positive result of hard work (успех).', 'success', null, '{"set": "challenge-v1", "word": "success", "pack": "content-2"}'),
  ('double-consonants', 'fill_gap', 'Her favourite ___ is painting. (хобби)', 'hobby', null, '{"set": "challenge-v1", "word": "hobby", "pack": "content-2"}'),
  ('double-consonants', 'multiple_choice', 'Choose the spelling of a short written communication.', 'message', '["message", "mesage", "messege"]', '{"set": "challenge-v1", "word": "message", "pack": "content-2"}'),
  ('vowel-order-ei-ie', 'correct_word', 'freind', 'friend', null, '{"set": "challenge-v1", "word": "friend", "pack": "content-2"}'),
  ('vowel-order-ei-ie', 'spell', 'Spell the word: land used to grow crops (поле).', 'field', null, '{"set": "challenge-v1", "word": "field", "pack": "content-2"}'),
  ('vowel-order-ei-ie', 'fill_gap', 'Keep the ___ after paying. (чек)', 'receipt', null, '{"set": "challenge-v1", "word": "receipt", "pack": "content-2"}'),
  ('vowel-order-ei-ie', 'multiple_choice', 'Choose the spelling of a strongly held idea.', 'belief', '["belief", "beleif", "belif"]', '{"set": "challenge-v1", "word": "belief", "pack": "content-2"}'),
  ('lose-vs-loose', 'fill_gap', 'Do not ___ your place in the queue.', 'lose', null, '{"set": "challenge-v1", "word": "lose", "pack": "content-2"}'),
  ('lose-vs-loose', 'fill_gap', 'The handle feels ___.', 'loose', null, '{"set": "challenge-v1", "word": "loose", "pack": "content-2"}'),
  ('lose-vs-loose', 'multiple_choice', 'Choose the word: We must not ___ hope.', 'lose', '["lose", "loose"]', '{"set": "challenge-v1", "word": "lose", "pack": "content-2"}'),
  ('lose-vs-loose', 'multiple_choice', 'Choose the word: This shirt is too ___.', 'loose', '["lose", "loose"]', '{"set": "challenge-v1", "word": "loose", "pack": "content-2"}'),
  ('plural-y-to-ies', 'correct_word', 'cherrys', 'cherries', null, '{"set": "challenge-v1", "word": "cherries", "pack": "content-2"}'),
  ('plural-y-to-ies', 'spell', 'Spell the plural of diary.', 'diaries', null, '{"set": "challenge-v1", "word": "diaries", "pack": "content-2"}'),
  ('plural-y-to-ies', 'fill_gap', 'The ___ were bright red. (ягоды)', 'berries', null, '{"set": "challenge-v1", "word": "berries", "pack": "content-2"}'),
  ('plural-y-to-ies', 'multiple_choice', 'Choose the plural of puppy.', 'puppies', '["puppies", "puppys", "puppyes"]', '{"set": "challenge-v1", "word": "puppies", "pack": "content-2"}'),
  ('irregular-past-go', 'fill_gap', 'Last week we ___ to the museum.', 'went', null, '{"set": "challenge-v1", "word": "went", "pack": "content-2"}'),
  ('irregular-past-go', 'fill_gap', 'My brother has already ___ home.', 'gone', null, '{"set": "challenge-v1", "word": "gone", "pack": "content-2"}'),
  ('irregular-past-go', 'multiple_choice', 'Choose the word: They ___ to class daily.', 'go', '["go", "went", "gone"]', '{"set": "challenge-v1", "word": "go", "pack": "content-2"}'),
  ('irregular-past-go', 'multiple_choice', 'Choose the word: She ___ out yesterday.', 'went', '["go", "went", "gone"]', '{"set": "challenge-v1", "word": "went", "pack": "content-2"}'),
  ('there-vs-their', 'fill_gap', '___ is a café nearby.', 'there', null, '{"set": "challenge-v1", "word": "there", "pack": "content-2"}'),
  ('there-vs-their', 'fill_gap', 'The children washed ___ hands.', 'their', null, '{"set": "challenge-v1", "word": "their", "pack": "content-2"}'),
  ('there-vs-their', 'multiple_choice', 'Choose the word: ___ waiting outside.', 'they''re', '["there", "their", "they''re"]', '{"set": "challenge-v1", "word": "they''re", "pack": "content-2"}'),
  ('there-vs-their', 'multiple_choice', 'Choose the word: Put it over ___.', 'there', '["there", "their", "they''re"]', '{"set": "challenge-v1", "word": "there", "pack": "content-2"}'),
  ('its-vs-its-contraction', 'fill_gap', 'The car lost ___ mirror.', 'its', null, '{"set": "challenge-v1", "word": "its", "pack": "content-2"}'),
  ('its-vs-its-contraction', 'fill_gap', '___ nearly time for dinner.', 'it''s', null, '{"set": "challenge-v1", "word": "it''s", "pack": "content-2"}'),
  ('its-vs-its-contraction', 'multiple_choice', 'Choose the word: The house lost ___ roof.', 'its', '["its", "it''s"]', '{"set": "challenge-v1", "word": "its", "pack": "content-2"}'),
  ('its-vs-its-contraction', 'multiple_choice', 'Choose the word: ___ raining outside.', 'it''s', '["its", "it''s"]', '{"set": "challenge-v1", "word": "it''s", "pack": "content-2"}'),
  ('your-vs-youre', 'fill_gap', 'Please bring ___ own pen.', 'your', null, '{"set": "challenge-v1", "word": "your", "pack": "content-2"}'),
  ('your-vs-youre', 'fill_gap', '___ right about the price.', 'you''re', null, '{"set": "challenge-v1", "word": "you''re", "pack": "content-2"}'),
  ('your-vs-youre', 'multiple_choice', 'Choose the word: Is this ___ seat?', 'your', '["your", "you''re"]', '{"set": "challenge-v1", "word": "your", "pack": "content-2"}'),
  ('your-vs-youre', 'multiple_choice', 'Choose the word: ___ welcome to stay.', 'you''re', '["your", "you''re"]', '{"set": "challenge-v1", "word": "you''re", "pack": "content-2"}'),
  ('affect-vs-effect', 'fill_gap', 'Poor sleep can ___ your mood.', 'affect', null, '{"set": "challenge-v1", "word": "affect", "pack": "content-2"}'),
  ('affect-vs-effect', 'fill_gap', 'The change had a clear ___ on us.', 'effect', null, '{"set": "challenge-v1", "word": "effect", "pack": "content-2"}'),
  ('affect-vs-effect', 'multiple_choice', 'Choose the word: Will rain ___ the event?', 'affect', '["affect", "effect"]', '{"set": "challenge-v1", "word": "affect", "pack": "content-2"}'),
  ('affect-vs-effect', 'multiple_choice', 'Choose the word: That had a strong ___.', 'effect', '["affect", "effect"]', '{"set": "challenge-v1", "word": "effect", "pack": "content-2"}'),
  ('silent-letters', 'correct_word', 'nife', 'knife', null, '{"set": "challenge-v1", "word": "knife", "pack": "content-2"}'),
  ('silent-letters', 'spell', 'Spell the word: a person who fought on horseback long ago.', 'knight', null, '{"set": "challenge-v1", "word": "knight", "pack": "content-2"}'),
  ('silent-letters', 'fill_gap', 'Write down your ___ to the question. (ответ)', 'answer', null, '{"set": "challenge-v1", "word": "answer", "pack": "content-2"}'),
  ('silent-letters', 'multiple_choice', 'Choose the correct spelling of a baby sheep.', 'lamb', '["lamb", "lam", "lamm"]', '{"set": "challenge-v1", "word": "lamb", "pack": "content-2"}'),
  ('drop-silent-e', 'correct_word', 'moveing', 'moving', null, '{"set": "challenge-v1", "word": "moving", "pack": "content-2"}'),
  ('drop-silent-e', 'spell', 'Spell the word: the -ing form of smile.', 'smiling', null, '{"set": "challenge-v1", "word": "smiling", "pack": "content-2"}'),
  ('drop-silent-e', 'fill_gap', 'She is ___ money for a bicycle. (копит)', 'saving', null, '{"set": "challenge-v1", "word": "saving", "pack": "content-2"}'),
  ('drop-silent-e', 'multiple_choice', 'Choose the -ing form of ride.', 'riding', '["riding", "rideing", "ridding"]', '{"set": "challenge-v1", "word": "riding", "pack": "content-2"}'),
  ('double-before-ing-ed', 'correct_word', 'runing', 'running', null, '{"set": "challenge-v1", "word": "running", "pack": "content-2"}'),
  ('double-before-ing-ed', 'spell', 'Spell the word: the -ed form of slip.', 'slipped', null, '{"set": "challenge-v1", "word": "slipped", "pack": "content-2"}'),
  ('double-before-ing-ed', 'fill_gap', 'The baby is ___ on the carpet. (сидит)', 'sitting', null, '{"set": "challenge-v1", "word": "sitting", "pack": "content-2"}'),
  ('double-before-ing-ed', 'multiple_choice', 'Choose the -ing form of swim.', 'swimming', '["swimming", "swiming", "swimminge"]', '{"set": "challenge-v1", "word": "swimming", "pack": "content-2"}'),
  ('suffix-ful', 'correct_word', 'hopefull', 'hopeful', null, '{"set": "challenge-v1", "word": "hopeful", "pack": "content-2"}'),
  ('suffix-ful', 'spell', 'Spell the word: feeling great joy.', 'joyful', null, '{"set": "challenge-v1", "word": "joyful", "pack": "content-2"}'),
  ('suffix-ful', 'fill_gap', 'Be ___ near the wet floor. (осторожен)', 'careful', null, '{"set": "challenge-v1", "word": "careful", "pack": "content-2"}'),
  ('suffix-ful', 'multiple_choice', 'Choose the spelling meaning giving help.', 'helpful', '["helpful", "helpfull", "helppful"]', '{"set": "challenge-v1", "word": "helpful", "pack": "content-2"}'),
  ('adverbs-ly', 'correct_word', 'quickley', 'quickly', null, '{"set": "challenge-v1", "word": "quickly", "pack": "content-2"}'),
  ('adverbs-ly', 'spell', 'Spell the adverb made from easy.', 'easily', null, '{"set": "challenge-v1", "word": "easily", "pack": "content-2"}'),
  ('adverbs-ly', 'fill_gap', 'The car moved ___ through town. (медленно)', 'slowly', null, '{"set": "challenge-v1", "word": "slowly", "pack": "content-2"}'),
  ('adverbs-ly', 'multiple_choice', 'Choose the adverb made from simple.', 'simply', '["simply", "simplely", "simpely"]', '{"set": "challenge-v1", "word": "simply", "pack": "content-2"}'),
  ('able-vs-ible', 'correct_word', 'accessable', 'accessible', null, '{"set": "challenge-v1", "word": "accessible", "pack": "content-2"}'),
  ('able-vs-ible', 'spell', 'Spell the word: able to be read.', 'readable', null, '{"set": "challenge-v1", "word": "readable", "pack": "content-2"}'),
  ('able-vs-ible', 'fill_gap', 'Her handwriting was ___ despite the rain. (разборчивым)', 'legible', null, '{"set": "challenge-v1", "word": "legible", "pack": "content-2"}'),
  ('able-vs-ible', 'multiple_choice', 'Choose the spelling meaning believable.', 'credible', '["credible", "credable", "credibel"]', '{"set": "challenge-v1", "word": "credible", "pack": "content-2"}')
) as v(slug, exercise_type, prompt, answer, choices, metadata)
join public.rules r on r.slug = v.slug
where not exists (select 1 from public.rule_exercises e where e.rule_id = r.id and e.exercise_type = v.exercise_type and e.prompt = v.prompt and e.answer = v.answer);

-- Exact identifiers from the supplied built-in CSV.
insert into public.rule_word_links (rule_id, word_id, relation, note)
select r.id, v.word_id, v.relation, v.note
from (values
  ('advice-vs-advise', 'general-english-confusable-words-advice', 'primary', 'Noun and verb have different endings'),
  ('advice-vs-advise', 'general-english-confusable-words-advise', 'primary', 'Noun and verb have different endings'),
  ('quiet-vs-quite', 'general-english-confusable-words-quiet', 'primary', 'Different meanings need different spellings'),
  ('quiet-vs-quite', 'general-english-confusable-words-quite', 'primary', 'Different meanings need different spellings'),
  ('weather-vs-whether', 'weather-and-seasons-weather-and-seasons-weather', 'primary', 'Conditions or choice determine the spelling'),
  ('weather-vs-whether', 'general-english-confusable-words-weather', 'primary', 'Conditions or choice determine the spelling'),
  ('weather-vs-whether', 'general-english-confusable-words-whether', 'primary', 'Conditions or choice determine the spelling'),
  ('principal-vs-principle', 'general-english-confusable-words-principal', 'primary', 'Main person or a guiding belief'),
  ('principal-vs-principle', 'general-english-confusable-words-principle', 'primary', 'Main person or a guiding belief'),
  ('stationary-vs-stationery', 'general-english-confusable-words-stationary', 'primary', 'Motion or writing determines the ending'),
  ('stationary-vs-stationery', 'general-english-confusable-words-stationery', 'primary', 'Motion or writing determines the ending'),
  ('lose-vs-loose', 'general-english-confusable-words-loose', 'primary', 'Verb and adjective differ by o'),
  ('lose-vs-loose', 'general-english-confusable-words-lose', 'primary', 'Verb and adjective differ by o'),
  ('affect-vs-effect', 'general-english-confusable-words-affect', 'primary', 'Action and result use different initials'),
  ('affect-vs-effect', 'general-english-confusable-words-effect', 'primary', 'Action and result use different initials'),
  ('there-vs-their', 'general-english-confusable-words-their', 'primary', 'Place and ownership have different forms'),
  ('there-vs-their', 'general-english-confusable-words-there', 'primary', 'Place and ownership have different forms'),
  ('double-consonants', 'general-english-professional-communication-communication', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'study-and-career-learning-and-research-assignment', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'travel-and-culture-at-the-destination-accommodation', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'everyday-life-home-and-services-appointment', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'food-and-drinks-meals-and-cooking-dessert', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'food-and-drinks-caf-and-restaurant-allergic', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'people-and-family-family-and-friends-colleague', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'feelings-feelings-embarrassed', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'feelings-feelings-disappointed', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'health-and-body-at-the-doctor-appointment', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'technology-devices-and-software-battery', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'technology-devices-and-software-install', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'nature-and-animals-nature-and-animals-butterfly', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'nature-and-animals-nature-and-animals-squirrel', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'weather-and-seasons-weather-and-seasons-drizzle', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'general-english-commonly-misspelled-accommodation', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'general-english-commonly-misspelled-occasionally', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'general-english-commonly-misspelled-necessary', 'primary', 'Contains a meaningful doubled consonant'),
  ('double-consonants', 'general-english-commonly-misspelled-embarrass', 'primary', 'Contains a meaningful doubled consonant'),
  ('vowel-order-ei-ie', 'everyday-life-home-and-services-receipt', 'primary', 'Check whether ie or ei appears'),
  ('vowel-order-ei-ie', 'people-and-family-family-and-friends-friendship', 'primary', 'Check whether ie or ei appears'),
  ('vowel-order-ei-ie', 'shopping-shopping-receipt', 'primary', 'Check whether ie or ei appears'),
  ('vowel-order-ei-ie', 'general-english-commonly-misspelled-receive', 'primary', 'Check whether ie or ei appears'),
  ('vowel-order-ei-ie', 'general-english-commonly-misspelled-achieve', 'primary', 'Check whether ie or ei appears'),
  ('vowel-order-ei-ie', 'general-english-commonly-misspelled-believe', 'primary', 'Check whether ie or ei appears'),
  ('vowel-order-ei-ie', 'people-and-family-family-and-friends-neighbour', 'related', 'Irregular ie or ei letter pattern'),
  ('vowel-order-ei-ie', 'general-english-commonly-misspelled-foreign', 'related', 'Irregular ie or ei letter pattern'),
  ('vowel-order-ei-ie', 'general-english-commonly-misspelled-weird', 'related', 'Irregular ie or ei letter pattern'),
  ('vowel-order-ei-ie', 'general-english-commonly-misspelled-neighbour', 'related', 'Irregular ie or ei letter pattern'),
  ('vowel-order-ei-ie', 'general-english-commonly-misspelled-conscience', 'related', 'Irregular ie or ei letter pattern'),
  ('silent-letters', 'home-around-the-house-cupboard', 'primary', 'A written consonant is not pronounced'),
  ('silent-letters', 'health-and-body-body-and-symptoms-knee', 'primary', 'A written consonant is not pronounced'),
  ('silent-letters', 'nature-and-animals-nature-and-animals-island', 'primary', 'A written consonant is not pronounced'),
  ('silent-letters', 'general-english-commonly-misspelled-knowledge', 'primary', 'A written consonant is not pronounced'),
  ('silent-letters', 'general-english-commonly-misspelled-answer', 'primary', 'A written consonant is not pronounced'),
  ('plural-y-to-ies', 'places-in-town-places-in-town-pharmacy', 'related', 'Plural changes consonant y to ies'),
  ('plural-y-to-ies', 'places-in-town-places-in-town-library', 'related', 'Plural changes consonant y to ies'),
  ('plural-y-to-ies', 'places-in-town-places-in-town-bakery', 'related', 'Plural changes consonant y to ies'),
  ('plural-y-to-ies', 'health-and-body-at-the-doctor-allergy', 'related', 'Plural changes consonant y to ies'),
  ('plural-y-to-ies', 'general-english-commonly-misspelled-library', 'related', 'Plural changes consonant y to ies'),
  ('tion-vs-sion', 'general-english-professional-communication-presentation', 'primary', 'Noun uses the tion ending'),
  ('tion-vs-sion', 'business-and-office-meetings-and-negotiation-negotiation', 'primary', 'Noun uses the tion ending'),
  ('tion-vs-sion', 'study-and-career-career-development-qualification', 'primary', 'Noun uses the tion ending'),
  ('tion-vs-sion', 'travel-and-culture-travel-planning-reservation', 'primary', 'Noun uses the tion ending'),
  ('tion-vs-sion', 'food-and-drinks-caf-and-restaurant-reservation', 'primary', 'Noun uses the tion ending'),
  ('tion-vs-sion', 'people-and-family-family-and-friends-generation', 'primary', 'Noun uses the tion ending'),
  ('tion-vs-sion', 'health-and-body-at-the-doctor-prescription', 'primary', 'Noun uses the tion ending'),
  ('tion-vs-sion', 'technology-online-life-notification', 'primary', 'Noun uses the tion ending'),
  ('tion-vs-sion', 'nature-and-animals-nature-and-animals-pollution', 'primary', 'Noun uses the tion ending'),
  ('tion-vs-sion', 'business-and-office-meetings-and-negotiation-customer-satisfaction', 'related', 'Contains the tion noun ending'),
  ('tion-vs-sion', 'travel-and-culture-at-the-destination-directions', 'related', 'Contains the tion noun ending'),
  ('comparatives-er-est', 'feelings-feelings-happy', 'primary', 'Happier changes final y to i'),
  ('plural-es', 'sport-and-fitness-training-and-competition-match', 'primary', 'Final ch takes es in plural'),
  ('double-before-ing-ed', 'shopping-shopping-fitting-room', 'related', 'Fit doubles t before ing'),
  ('drop-silent-e', 'weather-and-seasons-weather-and-seasons-freezing', 'primary', 'Freeze drops final e before ing'),
  ('suffix-ful', 'feelings-feelings-grateful', 'primary', 'The ful suffix has one l'),
  ('adverbs-ly', 'general-english-commonly-misspelled-definitely', 'related', 'Adverb is formed with final ly'),
  ('drop-silent-e', 'sport-and-fitness-training-and-competition-score', 'related', 'Final e is removed before ing'),
  ('drop-silent-e', 'food-and-drinks-meals-and-cooking-bake', 'related', 'Final e is removed before ing'),
  ('drop-silent-e', 'health-and-body-body-and-symptoms-sneeze', 'related', 'Final e is removed before ing'),
  ('drop-silent-e', 'technology-devices-and-software-update', 'related', 'Final e is removed before ing'),
  ('drop-silent-e', 'nature-and-animals-nature-and-animals-recycle', 'related', 'Final e is removed before ing'),
  ('drop-silent-e', 'general-english-commonly-misspelled-separate', 'related', 'Final e is removed before ing'),
  ('comparatives-er-est', 'feelings-feelings-proud', 'related', 'Comparative adjective follows this pattern'),
  ('comparatives-er-est', 'health-and-body-body-and-symptoms-dizzy', 'related', 'Comparative adjective follows this pattern'),
  ('comparatives-er-est', 'health-and-body-body-and-symptoms-sore', 'related', 'Comparative adjective follows this pattern'),
  ('comparatives-er-est', 'general-english-confusable-words-quiet', 'related', 'Comparative adjective follows this pattern'),
  ('silent-letters', 'travel-and-culture-at-the-destination-sightseeing', 'related', 'Silent gh occurs in sight'),
  ('plural-es', 'business-and-office-finance-and-planning-expenses', 'related', 'Final s sound takes es in plural'),
  ('soft-c-and-g', 'shopping-shopping-exchange', 'related', 'Change keeps e before able')
) as v(slug, word_id, relation, note)
join public.rules r on r.slug = v.slug
where not exists (select 1 from public.rule_word_links l where l.rule_id = r.id and l.word_id = v.word_id);


-- =====================================================================
-- Specific error patterns for the new spelling rules (added in review).
-- The app's classifier detects each of these precisely, so every pattern links to exactly one rule.
-- =====================================================================
insert into public.error_patterns (slug, tier, label, description) values
  ('plural_es', 'learning', 'Plural -es', 'Plural written with -s where -es is needed (boxs instead of boxes).'),
  ('f_to_ves', 'learning', 'f → ves', 'Plural of a word ending in f/fe written with -fs/-fes (knifes instead of knives).'),
  ('irregular_plural', 'learning', 'Irregular plural', 'A regular -s on an irregular plural (mans instead of men).'),
  ('irregular_past', 'learning', 'Irregular past', 'A regular -ed on an irregular verb (thinked instead of thought).'),
  ('comparative_spelling', 'learning', 'Comparative -er/-est', 'Spelling change before -er/-est missed (happyer, hoter, niceer).'),
  ('tion_sion', 'learning', '-tion or -sion', 'The wrong one of -tion and -sion (decition instead of decision).'),
  ('ance_ence', 'learning', '-ance or -ence', 'The wrong one of -ance/-ence or -ant/-ent (differance instead of difference).'),
  ('soft_c_g', 'learning', 'Soft c / g + e', 'The e that keeps c or g soft was dropped (noticable instead of noticeable).')
on conflict (slug) do nothing;

insert into public.error_pattern_rule_links (error_pattern_id, rule_id, note)
select p.id, r.id, v.note
from (values
  ('plural_es', 'plural-es', '-es after s, x, z, ch, sh'),
  ('f_to_ves', 'plural-f-to-ves', 'f/fe becomes ves'),
  ('irregular_plural', 'irregular-plurals', 'regular -s on an irregular plural'),
  ('irregular_past', 'irregular-past-common', 'regular -ed on an irregular verb'),
  ('comparative_spelling', 'comparatives-er-est', 'spelling change before -er/-est'),
  ('tion_sion', 'tion-vs-sion', '-tion versus -sion'),
  ('ance_ence', 'ance-vs-ence', '-ance/-ence and -ant/-ent'),
  ('soft_c_g', 'soft-c-and-g', 'e kept after soft c/g')
) as v(pattern_slug, rule_slug, note)
join public.error_patterns p on p.slug = v.pattern_slug
join public.rules r on r.slug = v.rule_slug
on conflict (error_pattern_id, rule_id) do nothing;

commit;
