-- Spell Sprint content pack 2 — part 3 of 4: exercises.
-- Run the parts in order (1 → 4). Each part is safe to run again.
begin;

insert into public.rule_exercises (rule_id, exercise_type, prompt, answer, choices, metadata)
select r.id, v.exercise_type, v.prompt, v.answer, v.choices::jsonb, v.metadata::jsonb
from (values
  ('advice-vs-advise', 'fill_gap', 'I need some ___ before deciding.', 'advice', null, '{"set": "challenge-v1", "word": "advice", "pack": "content-2"}'),
  ('advice-vs-advise', 'fill_gap', 'Can you ___ me about the course?', 'advise', null, '{"set": "challenge-v1", "word": "advise", "pack": "content-2"}'),
  ('advice-vs-advise', 'fill_gap', 'His ___ was very helpful.', 'advice', null, '{"set": "challenge-v1", "word": "advice", "pack": "content-2"}'),
  ('advice-vs-advise', 'fill_gap', 'Doctors often ___ patients to rest.', 'advise', null, '{"set": "challenge-v1", "word": "advise", "pack": "content-2"}'),
  ('advice-vs-advise', 'fill_gap', 'That was good ___.', 'advice', null, '{"set": "challenge-v1", "word": "advice", "pack": "content-2"}'),
  ('advice-vs-advise', 'multiple_choice', 'Choose the word: I asked for your ___.', 'advice', '["advice", "advise"]', '{"set": "challenge-v1", "word": "advice", "pack": "content-2"}'),
  ('advice-vs-advise', 'multiple_choice', 'Choose the word: They ___ us to wait.', 'advise', '["advice", "advise"]', '{"set": "challenge-v1", "word": "advise", "pack": "content-2"}'),
  ('advice-vs-advise', 'multiple_choice', 'Choose the word: Could you offer some ___?', 'advice', '["advice", "advise"]', '{"set": "challenge-v1", "word": "advice", "pack": "content-2"}'),
  ('accept-vs-except', 'fill_gap', 'Please ___ this gift.', 'accept', null, '{"set": "challenge-v1", "word": "accept", "pack": "content-2"}'),
  ('accept-vs-except', 'fill_gap', 'Everyone ___ me was ready.', 'except', null, '{"set": "challenge-v1", "word": "except", "pack": "content-2"}'),
  ('accept-vs-except', 'fill_gap', 'Will you ___ the invitation?', 'accept', null, '{"set": "challenge-v1", "word": "accept", "pack": "content-2"}'),
  ('accept-vs-except', 'fill_gap', 'The shop opens daily ___ Sunday.', 'except', null, '{"set": "challenge-v1", "word": "except", "pack": "content-2"}'),
  ('accept-vs-except', 'fill_gap', 'I cannot ___ that price.', 'accept', null, '{"set": "challenge-v1", "word": "accept", "pack": "content-2"}'),
  ('accept-vs-except', 'multiple_choice', 'Choose the word: I eat everything ___ fish.', 'except', '["accept", "except"]', '{"set": "challenge-v1", "word": "except", "pack": "content-2"}'),
  ('accept-vs-except', 'multiple_choice', 'Choose the word: Did they ___ your offer?', 'accept', '["accept", "except"]', '{"set": "challenge-v1", "word": "accept", "pack": "content-2"}'),
  ('accept-vs-except', 'multiple_choice', 'Choose the word: All seats ___ one were taken.', 'except', '["accept", "except"]', '{"set": "challenge-v1", "word": "except", "pack": "content-2"}'),
  ('then-vs-than', 'fill_gap', 'We ate and ___ left.', 'then', null, '{"set": "challenge-v1", "word": "then", "pack": "content-2"}'),
  ('then-vs-than', 'fill_gap', 'This costs more ___ that.', 'than', null, '{"set": "challenge-v1", "word": "than", "pack": "content-2"}'),
  ('then-vs-than', 'fill_gap', 'Wash your hands, ___ eat.', 'then', null, '{"set": "challenge-v1", "word": "then", "pack": "content-2"}'),
  ('then-vs-than', 'fill_gap', 'He is younger ___ his sister.', 'than', null, '{"set": "challenge-v1", "word": "than", "pack": "content-2"}'),
  ('then-vs-than', 'fill_gap', 'The lights went out; ___ it rained.', 'then', null, '{"set": "challenge-v1", "word": "then", "pack": "content-2"}'),
  ('then-vs-than', 'multiple_choice', 'Choose the word: I would rather walk ___ drive.', 'than', '["then", "than"]', '{"set": "challenge-v1", "word": "than", "pack": "content-2"}'),
  ('then-vs-than', 'multiple_choice', 'Choose the word: We can talk about it ___.', 'then', '["then", "than"]', '{"set": "challenge-v1", "word": "then", "pack": "content-2"}'),
  ('then-vs-than', 'multiple_choice', 'Choose the word: It was harder ___ expected.', 'than', '["then", "than"]', '{"set": "challenge-v1", "word": "than", "pack": "content-2"}'),
  ('quiet-vs-quite', 'fill_gap', 'Please stay ___ during the film.', 'quiet', null, '{"set": "challenge-v1", "word": "quiet", "pack": "content-2"}'),
  ('quiet-vs-quite', 'fill_gap', 'It is ___ warm today.', 'quite', null, '{"set": "challenge-v1", "word": "quite", "pack": "content-2"}'),
  ('quiet-vs-quite', 'fill_gap', 'The street is usually ___.', 'quiet', null, '{"set": "challenge-v1", "word": "quiet", "pack": "content-2"}'),
  ('quiet-vs-quite', 'fill_gap', 'She was ___ pleased.', 'quite', null, '{"set": "challenge-v1", "word": "quite", "pack": "content-2"}'),
  ('quiet-vs-quite', 'fill_gap', 'The room became ___ after six.', 'quiet', null, '{"set": "challenge-v1", "word": "quiet", "pack": "content-2"}'),
  ('quiet-vs-quite', 'multiple_choice', 'Choose the word: This tea is ___ hot.', 'quite', '["quiet", "quite"]', '{"set": "challenge-v1", "word": "quite", "pack": "content-2"}'),
  ('quiet-vs-quite', 'multiple_choice', 'Choose the word: Please be ___ during the test.', 'quiet', '["quiet", "quite"]', '{"set": "challenge-v1", "word": "quiet", "pack": "content-2"}'),
  ('quiet-vs-quite', 'multiple_choice', 'Choose the word: The task is ___ simple.', 'quite', '["quiet", "quite"]', '{"set": "challenge-v1", "word": "quite", "pack": "content-2"}'),
  ('weather-vs-whether', 'fill_gap', 'The ___ may change soon.', 'weather', null, '{"set": "challenge-v1", "word": "weather", "pack": "content-2"}'),
  ('weather-vs-whether', 'fill_gap', 'I cannot decide ___ to go.', 'whether', null, '{"set": "challenge-v1", "word": "whether", "pack": "content-2"}'),
  ('weather-vs-whether', 'fill_gap', 'We checked the ___ before leaving.', 'weather', null, '{"set": "challenge-v1", "word": "weather", "pack": "content-2"}'),
  ('weather-vs-whether', 'fill_gap', 'She asked ___ I needed help.', 'whether', null, '{"set": "challenge-v1", "word": "whether", "pack": "content-2"}'),
  ('weather-vs-whether', 'fill_gap', 'Bad ___ kept us inside.', 'weather', null, '{"set": "challenge-v1", "word": "weather", "pack": "content-2"}'),
  ('weather-vs-whether', 'multiple_choice', 'Choose the word: Tell me ___ you agree.', 'whether', '["weather", "whether"]', '{"set": "challenge-v1", "word": "whether", "pack": "content-2"}'),
  ('weather-vs-whether', 'multiple_choice', 'Choose the word: The ___ was lovely yesterday.', 'weather', '["weather", "whether"]', '{"set": "challenge-v1", "word": "weather", "pack": "content-2"}'),
  ('weather-vs-whether', 'multiple_choice', 'Choose the word: I do not know ___ he called.', 'whether', '["weather", "whether"]', '{"set": "challenge-v1", "word": "whether", "pack": "content-2"}'),
  ('principal-vs-principle', 'fill_gap', 'The school ___ welcomed us.', 'principal', null, '{"set": "challenge-v1", "word": "principal", "pack": "content-2"}'),
  ('principal-vs-principle', 'fill_gap', 'Fairness is a useful ___.', 'principle', null, '{"set": "challenge-v1", "word": "principle", "pack": "content-2"}'),
  ('principal-vs-principle', 'fill_gap', 'The ___ problem is the cost.', 'principal', null, '{"set": "challenge-v1", "word": "principal", "pack": "content-2"}'),
  ('principal-vs-principle', 'fill_gap', 'He refused to lie on ___.', 'principle', null, '{"set": "challenge-v1", "word": "principle", "pack": "content-2"}'),
  ('principal-vs-principle', 'fill_gap', 'The ___ spoke at the meeting.', 'principal', null, '{"set": "challenge-v1", "word": "principal", "pack": "content-2"}'),
  ('principal-vs-principle', 'multiple_choice', 'Choose the word: Our ___ reason is time.', 'principal', '["principal", "principle"]', '{"set": "challenge-v1", "word": "principal", "pack": "content-2"}'),
  ('principal-vs-principle', 'multiple_choice', 'Choose the word: It is a matter of ___.', 'principle', '["principal", "principle"]', '{"set": "challenge-v1", "word": "principle", "pack": "content-2"}'),
  ('principal-vs-principle', 'multiple_choice', 'Choose the word: The school ___ called home.', 'principal', '["principal", "principle"]', '{"set": "challenge-v1", "word": "principal", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'fill_gap', 'The bicycle was ___.', 'stationary', null, '{"set": "challenge-v1", "word": "stationary", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'fill_gap', 'She bought ___ for school.', 'stationery', null, '{"set": "challenge-v1", "word": "stationery", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'fill_gap', 'The bus remained ___.', 'stationary', null, '{"set": "challenge-v1", "word": "stationary", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'fill_gap', 'We keep ___ in the cupboard.', 'stationery', null, '{"set": "challenge-v1", "word": "stationery", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'fill_gap', 'The camera must stay ___.', 'stationary', null, '{"set": "challenge-v1", "word": "stationary", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'multiple_choice', 'Choose the word: We need new ___ for the office.', 'stationery', '["stationary", "stationery"]', '{"set": "challenge-v1", "word": "stationery", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'multiple_choice', 'Choose the word: The vehicle stayed ___.', 'stationary', '["stationary", "stationery"]', '{"set": "challenge-v1", "word": "stationary", "pack": "content-2"}'),
  ('stationary-vs-stationery', 'multiple_choice', 'Choose the word: Pens are a type of ___.', 'stationery', '["stationary", "stationery"]', '{"set": "challenge-v1", "word": "stationery", "pack": "content-2"}'),
  ('to-too-two', 'fill_gap', 'I need ___ buy milk.', 'to', null, '{"set": "challenge-v1", "word": "to", "pack": "content-2"}'),
  ('to-too-two', 'fill_gap', 'There are ___ chairs here.', 'two', null, '{"set": "challenge-v1", "word": "two", "pack": "content-2"}'),
  ('to-too-two', 'fill_gap', 'This soup is ___ hot.', 'too', null, '{"set": "challenge-v1", "word": "too", "pack": "content-2"}'),
  ('to-too-two', 'fill_gap', 'She went ___ the library.', 'to', null, '{"set": "challenge-v1", "word": "to", "pack": "content-2"}'),
  ('to-too-two', 'fill_gap', 'Can I come ___?', 'too', null, '{"set": "challenge-v1", "word": "too", "pack": "content-2"}'),
  ('to-too-two', 'multiple_choice', 'Choose the word: I have ___ tickets.', 'two', '["to", "too", "two"]', '{"set": "challenge-v1", "word": "two", "pack": "content-2"}'),
  ('to-too-two', 'multiple_choice', 'Choose the word: The box is ___ heavy.', 'too', '["to", "too", "two"]', '{"set": "challenge-v1", "word": "too", "pack": "content-2"}'),
  ('to-too-two', 'multiple_choice', 'Choose the word: We plan ___ leave.', 'to', '["to", "too", "two"]', '{"set": "challenge-v1", "word": "to", "pack": "content-2"}'),
  ('were-where-wear', 'fill_gap', 'We ___ late yesterday.', 'were', null, '{"set": "challenge-v1", "word": "were", "pack": "content-2"}'),
  ('were-where-wear', 'fill_gap', '___ is the nearest stop?', 'where', null, '{"set": "challenge-v1", "word": "where", "pack": "content-2"}'),
  ('were-where-wear', 'fill_gap', 'You should ___ a coat.', 'wear', null, '{"set": "challenge-v1", "word": "wear", "pack": "content-2"}'),
  ('were-where-wear', 'fill_gap', 'The children ___ excited.', 'were', null, '{"set": "challenge-v1", "word": "were", "pack": "content-2"}'),
  ('were-where-wear', 'fill_gap', 'Do you know ___ she lives?', 'where', null, '{"set": "challenge-v1", "word": "where", "pack": "content-2"}'),
  ('were-where-wear', 'multiple_choice', 'Choose the word: I always ___ comfortable shoes.', 'wear', '["were", "where", "wear"]', '{"set": "challenge-v1", "word": "wear", "pack": "content-2"}'),
  ('were-where-wear', 'multiple_choice', 'Choose the word: They ___ at home yesterday.', 'were', '["were", "where", "wear"]', '{"set": "challenge-v1", "word": "were", "pack": "content-2"}'),
  ('were-where-wear', 'multiple_choice', 'Choose the word: Tell me ___ you found it.', 'where', '["were", "where", "wear"]', '{"set": "challenge-v1", "word": "where", "pack": "content-2"}'),
  ('practice-vs-practise', 'fill_gap', 'I need more ___ before the exam.', 'practice', null, '{"set": "challenge-v1", "word": "practice", "pack": "content-2"}'),
  ('practice-vs-practise', 'fill_gap', 'We ___ every Tuesday.', 'practise', null, '{"set": "challenge-v1", "word": "practise", "pack": "content-2"}'),
  ('practice-vs-practise', 'fill_gap', 'Her piano ___ lasts an hour.', 'practice', null, '{"set": "challenge-v1", "word": "practice", "pack": "content-2"}'),
  ('practice-vs-practise', 'fill_gap', 'Try to ___ these words.', 'practise', null, '{"set": "challenge-v1", "word": "practise", "pack": "content-2"}'),
  ('practice-vs-practise', 'fill_gap', 'The team had extra ___ today.', 'practice', null, '{"set": "challenge-v1", "word": "practice", "pack": "content-2"}'),
  ('practice-vs-practise', 'multiple_choice', 'Choose the word: I ___ for an hour daily.', 'practise', '["practice", "practise"]', '{"set": "challenge-v1", "word": "practise", "pack": "content-2"}'),
  ('practice-vs-practise', 'multiple_choice', 'Choose the word: Regular ___ is useful.', 'practice', '["practice", "practise"]', '{"set": "challenge-v1", "word": "practice", "pack": "content-2"}'),
  ('practice-vs-practise', 'multiple_choice', 'Choose the word: You should ___ your pronunciation.', 'practise', '["practice", "practise"]', '{"set": "challenge-v1", "word": "practise", "pack": "content-2"}'),
  ('plural-es', 'correct_word', 'brushs', 'brushes', null, '{"set": "challenge-v1", "word": "brushes", "pack": "content-2"}'),
  ('plural-es', 'correct_word', 'kisss', 'kisses', null, '{"set": "challenge-v1", "word": "kisses", "pack": "content-2"}'),
  ('plural-es', 'correct_word', 'buss', 'buses', null, '{"set": "challenge-v1", "word": "buses", "pack": "content-2"}'),
  ('plural-es', 'spell', 'Spell the word: more than one fox.', 'foxes', null, '{"set": "challenge-v1", "word": "foxes", "pack": "content-2"}'),
  ('plural-es', 'spell', 'Spell the word: more than one glass.', 'glasses', null, '{"set": "challenge-v1", "word": "glasses", "pack": "content-2"}'),
  ('plural-es', 'fill_gap', 'The two ___ helped the team. (тренеры)', 'coaches', null, '{"set": "challenge-v1", "word": "coaches", "pack": "content-2"}'),
  ('plural-es', 'fill_gap', 'The new ___ looked smart. (платья)', 'dresses', null, '{"set": "challenge-v1", "word": "dresses", "pack": "content-2"}'),
  ('plural-es', 'multiple_choice', 'Choose the correct plural of quiz.', 'quizzes', '["quizzes", "quizs", "quizes"]', '{"set": "challenge-v1", "word": "quizzes", "pack": "content-2"}'),
  ('plural-f-to-ves', 'correct_word', 'shelfs', 'shelves', null, '{"set": "challenge-v1", "word": "shelves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'correct_word', 'lifes', 'lives', null, '{"set": "challenge-v1", "word": "lives", "pack": "content-2"}'),
  ('plural-f-to-ves', 'correct_word', 'wolfs', 'wolves', null, '{"set": "challenge-v1", "word": "wolves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'spell', 'Spell the word: more than one thief.', 'thieves', null, '{"set": "challenge-v1", "word": "thieves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'spell', 'Spell the word: more than one loaf.', 'loaves', null, '{"set": "challenge-v1", "word": "loaves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'fill_gap', 'The ___ turned yellow in autumn. (листья)', 'leaves', null, '{"set": "challenge-v1", "word": "leaves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'fill_gap', 'The ___ stood near their mothers. (телята)', 'calves', null, '{"set": "challenge-v1", "word": "calves", "pack": "content-2"}'),
  ('plural-f-to-ves', 'multiple_choice', 'Choose the correct plural of half.', 'halves', '["halves", "halfs", "halfes"]', '{"set": "challenge-v1", "word": "halves", "pack": "content-2"}'),
  ('irregular-plurals', 'correct_word', 'mans', 'men', null, '{"set": "challenge-v1", "word": "men", "pack": "content-2"}'),
  ('irregular-plurals', 'correct_word', 'womans', 'women', null, '{"set": "challenge-v1", "word": "women", "pack": "content-2"}'),
  ('irregular-plurals', 'correct_word', 'tooths', 'teeth', null, '{"set": "challenge-v1", "word": "teeth", "pack": "content-2"}'),
  ('irregular-plurals', 'spell', 'Spell the word: more than one foot.', 'feet', null, '{"set": "challenge-v1", "word": "feet", "pack": "content-2"}'),
  ('irregular-plurals', 'spell', 'Spell the word: more than one goose.', 'geese', null, '{"set": "challenge-v1", "word": "geese", "pack": "content-2"}'),
  ('irregular-plurals', 'fill_gap', 'Three ___ waited outside. (человека)', 'people', null, '{"set": "challenge-v1", "word": "people", "pack": "content-2"}'),
  ('irregular-plurals', 'fill_gap', 'The ___ played quietly. (дети)', 'children', null, '{"set": "challenge-v1", "word": "children", "pack": "content-2"}'),
  ('irregular-plurals', 'multiple_choice', 'Choose the correct plural of mouse.', 'mice', '["mice", "mouses", "mices"]', '{"set": "challenge-v1", "word": "mice", "pack": "content-2"}'),
  ('irregular-past-common', 'correct_word', 'thinked', 'thought', null, '{"set": "challenge-v1", "word": "thought", "pack": "content-2"}'),
  ('irregular-past-common', 'correct_word', 'bringed', 'brought', null, '{"set": "challenge-v1", "word": "brought", "pack": "content-2"}'),
  ('irregular-past-common', 'correct_word', 'catched', 'caught', null, '{"set": "challenge-v1", "word": "caught", "pack": "content-2"}'),
  ('irregular-past-common', 'spell', 'Spell the word: the past form of buy.', 'bought', null, '{"set": "challenge-v1", "word": "bought", "pack": "content-2"}'),
  ('irregular-past-common', 'spell', 'Spell the word: the past form of teach.', 'taught', null, '{"set": "challenge-v1", "word": "taught", "pack": "content-2"}'),
  ('irregular-past-common', 'fill_gap', 'She ___ her old bicycle last week. (продала)', 'sold', null, '{"set": "challenge-v1", "word": "sold", "pack": "content-2"}'),
  ('irregular-past-common', 'fill_gap', 'He ___ a letter yesterday. (написал)', 'wrote', null, '{"set": "challenge-v1", "word": "wrote", "pack": "content-2"}'),
  ('irregular-past-common', 'multiple_choice', 'Choose the correct past form of feel.', 'felt', '["felt", "feeled", "felled"]', '{"set": "challenge-v1", "word": "felt", "pack": "content-2"}'),
  ('comparatives-er-est', 'correct_word', 'hoter', 'hotter', null, '{"set": "challenge-v1", "word": "hotter", "pack": "content-2"}'),
  ('comparatives-er-est', 'correct_word', 'easyer', 'easier', null, '{"set": "challenge-v1", "word": "easier", "pack": "content-2"}'),
  ('comparatives-er-est', 'correct_word', 'niceer', 'nicer', null, '{"set": "challenge-v1", "word": "nicer", "pack": "content-2"}'),
  ('comparatives-er-est', 'spell', 'Spell the word: the comparative form of sad.', 'sadder', null, '{"set": "challenge-v1", "word": "sadder", "pack": "content-2"}'),
  ('comparatives-er-est', 'spell', 'Spell the word: the superlative form of funny.', 'funniest', null, '{"set": "challenge-v1", "word": "funniest", "pack": "content-2"}'),
  ('comparatives-er-est', 'fill_gap', 'Today is ___ than yesterday. (теплее)', 'warmer', null, '{"set": "challenge-v1", "word": "warmer", "pack": "content-2"}'),
  ('comparatives-er-est', 'fill_gap', 'This is the ___ street nearby. (самая узкая)', 'narrowest', null, '{"set": "challenge-v1", "word": "narrowest", "pack": "content-2"}'),
  ('comparatives-er-est', 'multiple_choice', 'Choose the comparative of heavy.', 'heavier', '["heavier", "heavyer", "heavyr"]', '{"set": "challenge-v1", "word": "heavier", "pack": "content-2"}'),
  ('tion-vs-sion', 'correct_word', 'celebrasion', 'celebration', null, '{"set": "challenge-v1", "word": "celebration", "pack": "content-2"}'),
  ('tion-vs-sion', 'correct_word', 'expantion', 'expansion', null, '{"set": "challenge-v1", "word": "expansion", "pack": "content-2"}'),
  ('tion-vs-sion', 'correct_word', 'confution', 'confusion', null, '{"set": "challenge-v1", "word": "confusion", "pack": "content-2"}'),
  ('tion-vs-sion', 'spell', 'Spell the word: a talk in which people share ideas.', 'discussion', null, '{"set": "challenge-v1", "word": "discussion", "pack": "content-2"}'),
  ('tion-vs-sion', 'spell', 'Spell the word: a choice made after thinking.', 'decision', null, '{"set": "challenge-v1", "word": "decision", "pack": "content-2"}'),
  ('tion-vs-sion', 'fill_gap', 'Her ___ was clear and short. (презентация)', 'presentation', null, '{"set": "challenge-v1", "word": "presentation", "pack": "content-2"}'),
  ('tion-vs-sion', 'fill_gap', 'His ___ surprised the group. (признание)', 'admission', null, '{"set": "challenge-v1", "word": "admission", "pack": "content-2"}'),
  ('tion-vs-sion', 'multiple_choice', 'Choose the correct spelling of a final result.', 'conclusion', '["conclusion", "conclution", "concluson"]', '{"set": "challenge-v1", "word": "conclusion", "pack": "content-2"}'),
  ('ance-vs-ence', 'correct_word', 'preferance', 'preference', null, '{"set": "challenge-v1", "word": "preference", "pack": "content-2"}'),
  ('ance-vs-ence', 'correct_word', 'attendence', 'attendance', null, '{"set": "challenge-v1", "word": "attendance", "pack": "content-2"}'),
  ('ance-vs-ence', 'correct_word', 'importence', 'importance', null, '{"set": "challenge-v1", "word": "importance", "pack": "content-2"}'),
  ('ance-vs-ence', 'spell', 'Spell the word: the ability to wait calmly.', 'patience', null, '{"set": "challenge-v1", "word": "patience", "pack": "content-2"}'),
  ('ance-vs-ence', 'spell', 'Spell the word: help offered to someone.', 'assistance', null, '{"set": "challenge-v1", "word": "assistance", "pack": "content-2"}'),
  ('ance-vs-ence', 'fill_gap', 'Her ___ grew with experience. (уверенность)', 'confidence', null, '{"set": "challenge-v1", "word": "confidence", "pack": "content-2"}'),
  ('ance-vs-ence', 'fill_gap', 'The room fell into ___. (тишину)', 'silence', null, '{"set": "challenge-v1", "word": "silence", "pack": "content-2"}'),
  ('ance-vs-ence', 'multiple_choice', 'Choose the correct spelling of the noun for being absent.', 'absence', '["absence", "absance", "absense"]', '{"set": "challenge-v1", "word": "absence", "pack": "content-2"}'),
  ('soft-c-and-g', 'correct_word', 'servicable', 'serviceable', null, '{"set": "challenge-v1", "word": "serviceable", "pack": "content-2"}'),
  ('soft-c-and-g', 'correct_word', 'knowledgable', 'knowledgeable', null, '{"set": "challenge-v1", "word": "knowledgeable", "pack": "content-2"}'),
  ('soft-c-and-g', 'correct_word', 'tracable', 'traceable', null, '{"set": "challenge-v1", "word": "traceable", "pack": "content-2"}'),
  ('soft-c-and-g', 'spell', 'Spell the word: easy to notice.', 'noticeable', null, '{"set": "challenge-v1", "word": "noticeable", "pack": "content-2"}'),
  ('soft-c-and-g', 'spell', 'Spell the word: brave in a difficult situation.', 'courageous', null, '{"set": "challenge-v1", "word": "courageous", "pack": "content-2"}'),
  ('soft-c-and-g', 'fill_gap', 'The worn part is easily ___. (заменяемая)', 'replaceable', null, '{"set": "challenge-v1", "word": "replaceable", "pack": "content-2"}'),
  ('soft-c-and-g', 'fill_gap', 'The new timetable is busy but ___. (посильный)', 'manageable', null, '{"set": "challenge-v1", "word": "manageable", "pack": "content-2"}'),
  ('soft-c-and-g', 'multiple_choice', 'Choose the spelling for able to change.', 'changeable', '["changeable", "changable", "changeible"]', '{"set": "challenge-v1", "word": "changeable", "pack": "content-2"}'),
  ('double-consonants', 'correct_word', 'adres', 'address', null, '{"set": "challenge-v1", "word": "address", "pack": "content-2"}'),
  ('double-consonants', 'spell', 'Spell the word: a positive result of hard work (успех).', 'success', null, '{"set": "challenge-v1", "word": "success", "pack": "content-2"}'),
  ('double-consonants', 'fill_gap', 'Her favourite ___ is painting. (хобби)', 'hobby', null, '{"set": "challenge-v1", "word": "hobby", "pack": "content-2"}'),
  ('double-consonants', 'multiple_choice', 'Choose the spelling of a short written communication.', 'message', '["message", "mesage", "messege"]', '{"set": "challenge-v1", "word": "message", "pack": "content-2"}'),
  ('vowel-order-ei-ie', 'correct_word', 'freind', 'friend', null, '{"set": "challenge-v1", "word": "friend", "pack": "content-2"}'),
  ('vowel-order-ei-ie', 'spell', 'Spell the word: land used to grow crops (поле).', 'field', null, '{"set": "challenge-v1", "word": "field", "pack": "content-2"}'),
  ('vowel-order-ei-ie', 'fill_gap', 'Keep the ___ after paying. (чек)', 'receipt', null, '{"set": "challenge-v1", "word": "receipt", "pack": "content-2"}'),
  ('vowel-order-ei-ie', 'multiple_choice', 'Choose the spelling of a strongly held idea.', 'belief', '["belief", "beleif", "belif"]', '{"set": "challenge-v1", "word": "belief", "pack": "content-2"}'),
  ('lose-vs-loose', 'fill_gap', 'Do not ___ your place in the queue.', 'lose', null, '{"set": "challenge-v1", "word": "lose", "pack": "content-2"}'),
  ('lose-vs-loose', 'fill_gap', 'The handle feels ___.', 'loose', null, '{"set": "challenge-v1", "word": "loose", "pack": "content-2"}'),
  ('lose-vs-loose', 'multiple_choice', 'Choose the word: We must not ___ hope.', 'lose', '["lose", "loose"]', '{"set": "challenge-v1", "word": "lose", "pack": "content-2"}'),
  ('lose-vs-loose', 'multiple_choice', 'Choose the word: This shirt is too ___.', 'loose', '["lose", "loose"]', '{"set": "challenge-v1", "word": "loose", "pack": "content-2"}'),
  ('plural-y-to-ies', 'correct_word', 'cherrys', 'cherries', null, '{"set": "challenge-v1", "word": "cherries", "pack": "content-2"}'),
  ('plural-y-to-ies', 'spell', 'Spell the plural of diary.', 'diaries', null, '{"set": "challenge-v1", "word": "diaries", "pack": "content-2"}'),
  ('plural-y-to-ies', 'fill_gap', 'The ___ were bright red. (ягоды)', 'berries', null, '{"set": "challenge-v1", "word": "berries", "pack": "content-2"}'),
  ('plural-y-to-ies', 'multiple_choice', 'Choose the plural of puppy.', 'puppies', '["puppies", "puppys", "puppyes"]', '{"set": "challenge-v1", "word": "puppies", "pack": "content-2"}'),
  ('irregular-past-go', 'fill_gap', 'Last week we ___ to the museum.', 'went', null, '{"set": "challenge-v1", "word": "went", "pack": "content-2"}'),
  ('irregular-past-go', 'fill_gap', 'My brother has already ___ home.', 'gone', null, '{"set": "challenge-v1", "word": "gone", "pack": "content-2"}'),
  ('irregular-past-go', 'multiple_choice', 'Choose the word: They ___ to class daily.', 'go', '["go", "went", "gone"]', '{"set": "challenge-v1", "word": "go", "pack": "content-2"}'),
  ('irregular-past-go', 'multiple_choice', 'Choose the word: She ___ out yesterday.', 'went', '["go", "went", "gone"]', '{"set": "challenge-v1", "word": "went", "pack": "content-2"}'),
  ('there-vs-their', 'fill_gap', '___ is a café nearby.', 'there', null, '{"set": "challenge-v1", "word": "there", "pack": "content-2"}'),
  ('there-vs-their', 'fill_gap', 'The children washed ___ hands.', 'their', null, '{"set": "challenge-v1", "word": "their", "pack": "content-2"}'),
  ('there-vs-their', 'multiple_choice', 'Choose the word: ___ waiting outside.', 'they''re', '["there", "their", "they''re"]', '{"set": "challenge-v1", "word": "they''re", "pack": "content-2"}'),
  ('there-vs-their', 'multiple_choice', 'Choose the word: Put it over ___.', 'there', '["there", "their", "they''re"]', '{"set": "challenge-v1", "word": "there", "pack": "content-2"}'),
  ('its-vs-its-contraction', 'fill_gap', 'The car lost ___ mirror.', 'its', null, '{"set": "challenge-v1", "word": "its", "pack": "content-2"}'),
  ('its-vs-its-contraction', 'fill_gap', '___ nearly time for dinner.', 'it''s', null, '{"set": "challenge-v1", "word": "it''s", "pack": "content-2"}'),
  ('its-vs-its-contraction', 'multiple_choice', 'Choose the word: The house lost ___ roof.', 'its', '["its", "it''s"]', '{"set": "challenge-v1", "word": "its", "pack": "content-2"}'),
  ('its-vs-its-contraction', 'multiple_choice', 'Choose the word: ___ raining outside.', 'it''s', '["its", "it''s"]', '{"set": "challenge-v1", "word": "it''s", "pack": "content-2"}'),
  ('your-vs-youre', 'fill_gap', 'Please bring ___ own pen.', 'your', null, '{"set": "challenge-v1", "word": "your", "pack": "content-2"}'),
  ('your-vs-youre', 'fill_gap', '___ right about the price.', 'you''re', null, '{"set": "challenge-v1", "word": "you''re", "pack": "content-2"}'),
  ('your-vs-youre', 'multiple_choice', 'Choose the word: Is this ___ seat?', 'your', '["your", "you''re"]', '{"set": "challenge-v1", "word": "your", "pack": "content-2"}'),
  ('your-vs-youre', 'multiple_choice', 'Choose the word: ___ welcome to stay.', 'you''re', '["your", "you''re"]', '{"set": "challenge-v1", "word": "you''re", "pack": "content-2"}'),
  ('affect-vs-effect', 'fill_gap', 'Poor sleep can ___ your mood.', 'affect', null, '{"set": "challenge-v1", "word": "affect", "pack": "content-2"}'),
  ('affect-vs-effect', 'fill_gap', 'The change had a clear ___ on us.', 'effect', null, '{"set": "challenge-v1", "word": "effect", "pack": "content-2"}'),
  ('affect-vs-effect', 'multiple_choice', 'Choose the word: Will rain ___ the event?', 'affect', '["affect", "effect"]', '{"set": "challenge-v1", "word": "affect", "pack": "content-2"}'),
  ('affect-vs-effect', 'multiple_choice', 'Choose the word: That had a strong ___.', 'effect', '["affect", "effect"]', '{"set": "challenge-v1", "word": "effect", "pack": "content-2"}'),
  ('silent-letters', 'correct_word', 'nife', 'knife', null, '{"set": "challenge-v1", "word": "knife", "pack": "content-2"}'),
  ('silent-letters', 'spell', 'Spell the word: a person who fought on horseback long ago.', 'knight', null, '{"set": "challenge-v1", "word": "knight", "pack": "content-2"}'),
  ('silent-letters', 'fill_gap', 'Write down your ___ to the question. (ответ)', 'answer', null, '{"set": "challenge-v1", "word": "answer", "pack": "content-2"}'),
  ('silent-letters', 'multiple_choice', 'Choose the correct spelling of a baby sheep.', 'lamb', '["lamb", "lam", "lamm"]', '{"set": "challenge-v1", "word": "lamb", "pack": "content-2"}'),
  ('drop-silent-e', 'correct_word', 'moveing', 'moving', null, '{"set": "challenge-v1", "word": "moving", "pack": "content-2"}'),
  ('drop-silent-e', 'spell', 'Spell the word: the -ing form of smile.', 'smiling', null, '{"set": "challenge-v1", "word": "smiling", "pack": "content-2"}'),
  ('drop-silent-e', 'fill_gap', 'She is ___ money for a bicycle. (копит)', 'saving', null, '{"set": "challenge-v1", "word": "saving", "pack": "content-2"}'),
  ('drop-silent-e', 'multiple_choice', 'Choose the -ing form of ride.', 'riding', '["riding", "rideing", "ridding"]', '{"set": "challenge-v1", "word": "riding", "pack": "content-2"}'),
  ('double-before-ing-ed', 'correct_word', 'runing', 'running', null, '{"set": "challenge-v1", "word": "running", "pack": "content-2"}'),
  ('double-before-ing-ed', 'spell', 'Spell the word: the -ed form of slip.', 'slipped', null, '{"set": "challenge-v1", "word": "slipped", "pack": "content-2"}'),
  ('double-before-ing-ed', 'fill_gap', 'The baby is ___ on the carpet. (сидит)', 'sitting', null, '{"set": "challenge-v1", "word": "sitting", "pack": "content-2"}'),
  ('double-before-ing-ed', 'multiple_choice', 'Choose the -ing form of swim.', 'swimming', '["swimming", "swiming", "swimminge"]', '{"set": "challenge-v1", "word": "swimming", "pack": "content-2"}'),
  ('suffix-ful', 'correct_word', 'hopefull', 'hopeful', null, '{"set": "challenge-v1", "word": "hopeful", "pack": "content-2"}'),
  ('suffix-ful', 'spell', 'Spell the word: feeling great joy.', 'joyful', null, '{"set": "challenge-v1", "word": "joyful", "pack": "content-2"}'),
  ('suffix-ful', 'fill_gap', 'Be ___ near the wet floor. (осторожен)', 'careful', null, '{"set": "challenge-v1", "word": "careful", "pack": "content-2"}'),
  ('suffix-ful', 'multiple_choice', 'Choose the spelling meaning giving help.', 'helpful', '["helpful", "helpfull", "helppful"]', '{"set": "challenge-v1", "word": "helpful", "pack": "content-2"}'),
  ('adverbs-ly', 'correct_word', 'quickley', 'quickly', null, '{"set": "challenge-v1", "word": "quickly", "pack": "content-2"}'),
  ('adverbs-ly', 'spell', 'Spell the adverb made from easy.', 'easily', null, '{"set": "challenge-v1", "word": "easily", "pack": "content-2"}'),
  ('adverbs-ly', 'fill_gap', 'The car moved ___ through town. (медленно)', 'slowly', null, '{"set": "challenge-v1", "word": "slowly", "pack": "content-2"}'),
  ('adverbs-ly', 'multiple_choice', 'Choose the adverb made from simple.', 'simply', '["simply", "simplely", "simpely"]', '{"set": "challenge-v1", "word": "simply", "pack": "content-2"}'),
  ('able-vs-ible', 'correct_word', 'accessable', 'accessible', null, '{"set": "challenge-v1", "word": "accessible", "pack": "content-2"}'),
  ('able-vs-ible', 'spell', 'Spell the word: able to be read.', 'readable', null, '{"set": "challenge-v1", "word": "readable", "pack": "content-2"}'),
  ('able-vs-ible', 'fill_gap', 'Her handwriting was ___ despite the rain. (разборчивым)', 'legible', null, '{"set": "challenge-v1", "word": "legible", "pack": "content-2"}'),
  ('able-vs-ible', 'multiple_choice', 'Choose the spelling meaning believable.', 'credible', '["credible", "credable", "credibel"]', '{"set": "challenge-v1", "word": "credible", "pack": "content-2"}')
) as v(slug, exercise_type, prompt, answer, choices, metadata)
join public.rules r on r.slug = v.slug
where not exists (select 1 from public.rule_exercises e where e.rule_id = r.id and e.exercise_type = v.exercise_type and e.prompt = v.prompt and e.answer = v.answer);

commit;
