-- Spell Sprint content pack 2 — part 2 of 4: examples.
-- Run the parts in order (1 → 4). Each part is safe to run again.
begin;

insert into public.rule_examples (rule_id, example_type, text, correction, note)
select r.id, v.example_type, v.text, v.correction, v.note
from (values
  ('advice-vs-advise', 'incorrect', 'I need your advise.', 'I need your advice.', 'The meaning selects this word'),
  ('advice-vs-advise', 'incorrect', 'Please advice me.', 'Please advise me.', 'The meaning selects this word'),
  ('advice-vs-advise', 'correct', 'Her advice helped me choose a course.', null, 'Correct word in context'),
  ('advice-vs-advise', 'correct', 'I advise you to check the details.', null, 'Correct word in context'),
  ('accept-vs-except', 'incorrect', 'I will except the offer.', 'I will accept the offer.', 'The meaning selects this word'),
  ('accept-vs-except', 'incorrect', 'Everyone came accept me.', 'Everyone came except me.', 'The meaning selects this word'),
  ('accept-vs-except', 'correct', 'She decided to accept the invitation.', null, 'Correct word in context'),
  ('accept-vs-except', 'correct', 'All the shops were open except one.', null, 'Correct word in context'),
  ('then-vs-than', 'incorrect', 'She is taller then me.', 'She is taller than me.', 'The meaning selects this word'),
  ('then-vs-than', 'incorrect', 'We ate and than left.', 'We ate and then left.', 'The meaning selects this word'),
  ('then-vs-than', 'correct', 'We finished dinner, then went home.', null, 'Correct word in context'),
  ('then-vs-than', 'correct', 'This coat is warmer than mine.', null, 'Correct word in context'),
  ('quiet-vs-quite', 'incorrect', 'The room was quite after lunch.', 'The room was quiet after lunch.', 'The meaning selects this word'),
  ('quiet-vs-quite', 'incorrect', 'The film was quiet interesting.', 'The film was quite interesting.', 'The meaning selects this word'),
  ('quiet-vs-quite', 'correct', 'The library is quiet in the morning.', null, 'Correct word in context'),
  ('quiet-vs-quite', 'correct', 'The book was quite interesting.', null, 'Correct word in context'),
  ('weather-vs-whether', 'incorrect', 'I wonder weather she is home.', 'I wonder whether she is home.', 'The meaning selects this word'),
  ('weather-vs-whether', 'incorrect', 'The whether is cold today.', 'The weather is cold today.', 'The meaning selects this word'),
  ('weather-vs-whether', 'correct', 'The weather improved before our walk.', null, 'Correct word in context'),
  ('weather-vs-whether', 'correct', 'I asked whether the shop was open.', null, 'Correct word in context'),
  ('principal-vs-principle', 'incorrect', 'Honesty is an important principal.', 'Honesty is an important principle.', 'The meaning selects this word'),
  ('principal-vs-principle', 'incorrect', 'The principle reason was cost.', 'The principal reason was cost.', 'The meaning selects this word'),
  ('principal-vs-principle', 'correct', 'The principal reason was the price.', null, 'Correct word in context'),
  ('principal-vs-principle', 'correct', 'Fairness is an important principle.', null, 'Correct word in context'),
  ('stationary-vs-stationery', 'incorrect', 'The car stayed stationery.', 'The car stayed stationary.', 'The meaning selects this word'),
  ('stationary-vs-stationery', 'incorrect', 'We need more stationary for the office.', 'We need more stationery for the office.', 'The meaning selects this word'),
  ('stationary-vs-stationery', 'correct', 'The train remained stationary at the platform.', null, 'Correct word in context'),
  ('stationary-vs-stationery', 'correct', 'I bought stationery for my class.', null, 'Correct word in context'),
  ('to-too-two', 'incorrect', 'I have to sisters.', 'I have two sisters.', 'The meaning selects this word'),
  ('to-too-two', 'incorrect', 'This bag is two heavy.', 'This bag is too heavy.', 'The meaning selects this word'),
  ('to-too-two', 'correct', 'We walked to the park after lunch.', null, 'Correct word in context'),
  ('to-too-two', 'correct', 'The two boys wanted to come too.', null, 'Correct word in context'),
  ('were-where-wear', 'incorrect', 'Where you at home yesterday?', 'Were you at home yesterday?', 'The meaning selects this word'),
  ('were-where-wear', 'incorrect', 'I will where a coat.', 'I will wear a coat.', 'The meaning selects this word'),
  ('were-where-wear', 'correct', 'We were tired after the walk.', null, 'Correct word in context'),
  ('were-where-wear', 'correct', 'Where do you wear that jacket?', null, 'Correct word in context'),
  ('practice-vs-practise', 'incorrect', 'Daily practise is useful.', 'Daily practice is useful.', 'The meaning selects this word'),
  ('practice-vs-practise', 'incorrect', 'I want to practice speaking.', 'I want to practise speaking.', 'The meaning selects this word'),
  ('practice-vs-practise', 'correct', 'Regular practice improves spelling.', null, 'Correct word in context'),
  ('practice-vs-practise', 'correct', 'I practise speaking English each morning.', null, 'Correct word in context'),
  ('plural-es', 'incorrect', 'boxs', 'boxes', 'Correct the spelling of this form'),
  ('plural-es', 'incorrect', 'watchs', 'watches', 'Correct the spelling of this form'),
  ('plural-es', 'correct', 'We packed the boxes before lunch.', null, 'Correct spelling in context'),
  ('plural-es', 'correct', 'She wears two watches on special occasions.', null, 'Correct spelling in context'),
  ('plural-es', 'exception', 'stomach → stomachs', null, 'Hard ch sound takes only s'),
  ('plural-f-to-ves', 'incorrect', 'knifes', 'knives', 'Correct the spelling of this form'),
  ('plural-f-to-ves', 'incorrect', 'wifes', 'wives', 'Correct the spelling of this form'),
  ('plural-f-to-ves', 'correct', 'The knives are in the kitchen drawer.', null, 'Correct spelling in context'),
  ('plural-f-to-ves', 'correct', 'Several leaves fell from the tree.', null, 'Correct spelling in context'),
  ('plural-f-to-ves', 'exception', 'roof → roofs; chef → chefs', null, 'These nouns keep f and add s'),
  ('irregular-plurals', 'incorrect', 'childs', 'children', 'Correct the spelling of this form'),
  ('irregular-plurals', 'incorrect', 'mouses', 'mice', 'Correct the spelling of this form'),
  ('irregular-plurals', 'correct', 'The children played outside all afternoon.', null, 'Correct spelling in context'),
  ('irregular-plurals', 'correct', 'Two mice ran across the floor.', null, 'Correct spelling in context'),
  ('irregular-past-common', 'incorrect', 'buyed', 'bought', 'Correct the spelling of this form'),
  ('irregular-past-common', 'incorrect', 'teached', 'taught', 'Correct the spelling of this form'),
  ('irregular-past-common', 'correct', 'She bought some bread yesterday.', null, 'Correct spelling in context'),
  ('irregular-past-common', 'correct', 'The teacher taught us a new song.', null, 'Correct spelling in context'),
  ('comparatives-er-est', 'incorrect', 'biger', 'bigger', 'Correct the spelling of this form'),
  ('comparatives-er-est', 'incorrect', 'happyer', 'happier', 'Correct the spelling of this form'),
  ('comparatives-er-est', 'correct', 'This room is bigger than ours.', null, 'Correct spelling in context'),
  ('comparatives-er-est', 'correct', 'She chose the nicest cake.', null, 'Correct spelling in context'),
  ('comparatives-er-est', 'exception', 'good → better → best', null, 'Good uses irregular comparison forms'),
  ('tion-vs-sion', 'incorrect', 'informasion', 'information', 'Correct the spelling of this form'),
  ('tion-vs-sion', 'incorrect', 'decition', 'decision', 'Correct the spelling of this form'),
  ('tion-vs-sion', 'correct', 'The information was easy to find.', null, 'Correct spelling in context'),
  ('tion-vs-sion', 'correct', 'We had a discussion after the film.', null, 'Correct spelling in context'),
  ('ance-vs-ence', 'incorrect', 'appearence', 'appearance', 'Correct the spelling of this form'),
  ('ance-vs-ence', 'incorrect', 'independance', 'independence', 'Correct the spelling of this form'),
  ('ance-vs-ence', 'correct', 'Her appearance changed over the years.', null, 'Correct spelling in context'),
  ('ance-vs-ence', 'correct', 'Their independence matters to them.', null, 'Correct spelling in context'),
  ('soft-c-and-g', 'incorrect', 'noticable', 'noticeable', 'Correct the spelling of this form'),
  ('soft-c-and-g', 'incorrect', 'couragous', 'courageous', 'Correct the spelling of this form'),
  ('soft-c-and-g', 'correct', 'The change was noticeable after a week.', null, 'Correct spelling in context'),
  ('soft-c-and-g', 'correct', 'It was courageous of her to speak up.', null, 'Correct spelling in context'),
  ('double-consonants', 'incorrect', 'adress', 'address', 'Correct the relevant rule here'),
  ('double-consonants', 'incorrect', 'succes', 'success', 'Correct the relevant rule here'),
  ('double-consonants', 'correct', 'Write your address clearly on the form.', null, 'Correct use in context'),
  ('vowel-order-ei-ie', 'incorrect', 'recieve', 'receive', 'Correct the relevant rule here'),
  ('vowel-order-ei-ie', 'incorrect', 'freind', 'friend', 'Correct the relevant rule here'),
  ('vowel-order-ei-ie', 'correct', 'My friend waited near the entrance.', null, 'Correct use in context'),
  ('lose-vs-loose', 'incorrect', 'Do not loose the ticket.', 'Do not lose the ticket.', 'Correct the relevant rule here'),
  ('lose-vs-loose', 'incorrect', 'The rope is lose.', 'The rope is loose.', 'Correct the relevant rule here'),
  ('lose-vs-loose', 'correct', 'The lid was loose, so I nearly lost it.', null, 'Correct use in context'),
  ('plural-y-to-ies', 'incorrect', 'cherrys', 'cherries', 'Correct the relevant rule here'),
  ('plural-y-to-ies', 'incorrect', 'dairys', 'dairies', 'Correct the relevant rule here'),
  ('plural-y-to-ies', 'correct', 'The berries were fresh and sweet.', null, 'Correct use in context'),
  ('irregular-past-go', 'incorrect', 'She goed home.', 'She went home.', 'Correct the relevant rule here'),
  ('irregular-past-go', 'incorrect', 'He has went home.', 'He has gone home.', 'Correct the relevant rule here'),
  ('irregular-past-go', 'correct', 'After lunch, they went to the park.', null, 'Correct use in context'),
  ('there-vs-their', 'incorrect', 'The coats are over their.', 'The coats are over there.', 'Correct the relevant rule here'),
  ('there-vs-their', 'incorrect', 'There house is small.', 'Their house is small.', 'Correct the relevant rule here'),
  ('there-vs-their', 'correct', 'They left their coats there by the door.', null, 'Correct use in context'),
  ('its-vs-its-contraction', 'incorrect', 'Its a sunny day.', 'It''s a sunny day.', 'Correct the relevant rule here'),
  ('its-vs-its-contraction', 'incorrect', 'The dog ate it''s food.', 'The dog ate its food.', 'Correct the relevant rule here'),
  ('its-vs-its-contraction', 'correct', 'The bird opened its wings because it''s ready to fly.', null, 'Correct use in context'),
  ('your-vs-youre', 'incorrect', 'Your very kind.', 'You''re very kind.', 'Correct the relevant rule here'),
  ('your-vs-youre', 'incorrect', 'You''re bag is heavy.', 'Your bag is heavy.', 'Correct the relevant rule here'),
  ('your-vs-youre', 'correct', 'Your brother said you''re coming soon.', null, 'Correct use in context'),
  ('affect-vs-effect', 'incorrect', 'Noise can effect sleep.', 'Noise can affect sleep.', 'Correct the relevant rule here'),
  ('affect-vs-effect', 'incorrect', 'The new rule had an affect.', 'The new rule had an effect.', 'Correct the relevant rule here'),
  ('affect-vs-effect', 'correct', 'The cold may affect how quickly the medicine takes effect.', null, 'Correct use in context'),
  ('silent-letters', 'incorrect', 'nife', 'knife', 'Correct the relevant rule here'),
  ('silent-letters', 'incorrect', 'lam', 'lamb', 'Keep the silent final b'),
  ('silent-letters', 'correct', 'The lamb slept beside the old fence.', null, 'Correct use in context'),
  ('drop-silent-e', 'incorrect', 'moveing', 'moving', 'Correct the relevant rule here'),
  ('drop-silent-e', 'incorrect', 'hopeing', 'hoping', 'Correct the relevant rule here'),
  ('drop-silent-e', 'correct', 'She smiled while moving the chairs.', null, 'Correct use in context'),
  ('double-before-ing-ed', 'incorrect', 'runing', 'running', 'Correct the relevant rule here'),
  ('double-before-ing-ed', 'incorrect', 'sliped', 'slipped', 'Correct the relevant rule here'),
  ('double-before-ing-ed', 'correct', 'They were running through the park together.', null, 'Correct use in context'),
  ('suffix-ful', 'incorrect', 'hopefull', 'hopeful', 'Correct the relevant rule here'),
  ('suffix-ful', 'incorrect', 'cheerfull', 'cheerful', 'Correct the relevant rule here'),
  ('suffix-ful', 'correct', 'Her cheerful voice made everyone smile.', null, 'Correct use in context'),
  ('adverbs-ly', 'incorrect', 'quickley', 'quickly', 'Correct the relevant rule here'),
  ('adverbs-ly', 'incorrect', 'slowley', 'slowly', 'Correct the relevant rule here'),
  ('adverbs-ly', 'correct', 'She answered the question quickly and clearly.', null, 'Correct use in context'),
  ('able-vs-ible', 'incorrect', 'accessable', 'accessible', 'Correct the relevant rule here'),
  ('able-vs-ible', 'incorrect', 'readible', 'readable', 'Correct the relevant rule here'),
  ('able-vs-ible', 'correct', 'The menu was readable even in poor light.', null, 'Correct use in context')
) as v(slug, example_type, text, correction, note)
join public.rules r on r.slug = v.slug
where not exists (select 1 from public.rule_examples e where e.rule_id = r.id and e.example_type = v.example_type and e.text = v.text);

commit;
